nerfstudio/configs/method_configs.py

Mistake from prematurely merged #667, sorry!!

Remove unused rich import

---

README.md
docs/quickstart/installation.md

Overall awesome work!
In this PR.
1. Fixed a small typo in the README.md
2. Added commends to upgrade pip and setuptools into the "install from source" sections
I wasn't able to actually run anything because I didn't have a GPU
Other comments -- feel free to take or leave :)
1. It doesn't look like conda is used for any dependencies, so I'd remove that from the README.md, and instead recommend to use pip / virtualenv directly.
2. Add maximum versions to any range dependencies in the pyproject.toml (e.g. h5py, appdirs, dcargs, ...) or use strict version pinning. Also, `requests` should have a version.
3. All the `python scripts/train.py` commands don't work -- getting errors along the lines of:
> `train.py: error: unrecognized arguments: --config-name=graph_instant_ngp.yaml`
4.  Thoughts …

Installation Docs Updates

---

nerfstudio/model_components/scene_colliders.py

We shouldn't clip the near plane during eval.

Don't apply near plane during eval

---

nerfstudio/configs/method_configs.py
nerfstudio/engine/trainer.py

max number of iterations logic

---

nerfstudio/cameras/camera_optimizers.py
nerfstudio/configs/method_configs.py
scripts/downloads/download_data.py

Only enable camera opt for nerfacto.

update camera opt defaults

---

scripts/viewer/view_dataset.py

Fixes to account for some recent code refactor + errors I made when resolving merge conflicts in #568 :face_with_spiral_eyes:

Fix view_dataset.py

---

README.md
scripts/process_data.py

- handles filenames properly
- copy the mp4 to the output folder

Improve process data with filename filters and saving mp4s

---

nerfstudio/configs/base_config.py
nerfstudio/engine/trainer.py
nerfstudio/utils/misc.py

- use a flag `--trainer.save_only_latest_checkpoint` instead of saving X last checkpoints

Improving checkpoint logic

---

nerfstudio/cameras/camera_utils.py

About 6ms faster per step (somewhere 10-15% speedup overall)

Add PyTorch jit-ing to the undistort computation for speed

---

README.md
docs/quickstart/custom_dataset.md
docs/reference/cli/index.md
nerfstudio/fields/nerfacto_field.py
scripts/process_data.py

This PR adds support for processing insta360 data.
Additionally the `ns-process-data` cli has been changed. It is now necessary to specify the dataset type, ie
```
ns-process-data {images,video,insta360} --data {DATA} --output-dir {OUTPUT}
```

Add support for insta360 data

---

scripts/process_data.py

Refining the intrinsics in colmap helps improve the final reconstruction sharpness.
Before:
After:

Refine intrinsics with COLMAP

---

nerfstudio/viewer/app/src/index.scss

Currently the inside is colored which is counterintuitive.

Color outside of render view

---

nerfstudio/cameras/rays.py

Small tweaks to get a 5% speedup on nerfacto. Found with @kerrj

Speedup get_ray_sample

---

README.md
docs/quickstart/installation.md
nerfstudio/cameras/camera_optimizers.py
nerfstudio/cameras/camera_utils.py
nerfstudio/configs/base_config.py
nerfstudio/data/dataparsers/nerfstudio_dataparser.py
nerfstudio/data/dataparsers/record3d_dataparser.py
nerfstudio/field_components/encodings.py
nerfstudio/model_components/renderers.py
nerfstudio/models/nerfacto.py
pyproject.toml
scripts/completions/install.py
scripts/downloads/download_data.py
scripts/process_data.py
scripts/render.py

We aren't using much 3.8 functionality. This PR lowers the requirement to >=3.7.3 (TorchTyping breaks if you go lower)

Support python 3.7

---

nerfstudio/viewer/server/viewer_utils.py

```python
from nerfstudio.viewer.server.viewer_utils import get_viewer_version
```

Add viewer version function

---

nerfstudio/viewer/app/src/index.scss
nerfstudio/viewer/app/src/modules/SidePanel/CameraPanel/CameraPanel.jsx
nerfstudio/viewer/app/src/modules/SidePanel/ScenePanel/ScenePanel.jsx
nerfstudio/viewer/app/src/modules/SidePanel/ScenePanel/index.jsx
nerfstudio/viewer/app/src/modules/SidePanel/SidePanel.jsx
nerfstudio/viewer/app/src/themes/theme.ts

Update viewer UI

---

docs/quickstart/first_nerf.md
nerfstudio/data/datamanagers.py
nerfstudio/engine/trainer.py
nerfstudio/pipelines/base_pipeline.py
nerfstudio/utils/comms.py
nerfstudio/utils/writer.py
scripts/train.py
tests/test_train.py

[DDP](https://pytorch.org/tutorials/beginner/dist_overview.html) seems to be working, but it only really makes sense for long or compute-heavy training runs. Here is a small test for only 1K iterations with vanilla-nerf.
```python
ns-train vanilla-nerf --machine.num-gpus 3 --vis wandb --trainer.max-num-iterations 1000 --optimizers.fields.optimizer.lr 15e-4 --trainer.steps-per-eval-batch 100 --trainer.steps-per-eval-image 100 --logging.local-writer.max-log-size=0
ns-train vanilla-nerf --machine.num-gpus 1 --vis wandb --trainer.max-num-iterations 1000 --optimizers.fields.optimizer.lr 5e-4 --trainer.steps-per-eval-batch 100 --trainer.steps-per-eval-image 100 --logging.local-writer.max-log-size=0
```

Multi-gpu improvements

---

scripts/downloads/download_data.py

Adds the ability to download the D-NeRF dataset for dynamic NeRFs.
I know there's currently no way to render dynamic nerf modules, but I would like to attempt adding them later.

Add D-NeRF dataset download

---

nerfstudio/cameras/camera_utils.py

@tancik Minor bug fix for #800 .

Fix pose translation when orientation_method=none

---

nerfstudio/model_components/renderers.py

Normalize depth for packed samples

---

scripts/eval.py

Updates the comments in scripts/eval.py as some in my opinion can be organized better and gramatically better.

docs(scripts/eval.py) Update comments

---

.github/workflows/publish.yml
README.md

Publish to pypi when new github version is created.

Add github pypi publish action

---

README.md
colab/demo.ipynb
docs/_templates/sidebar/brand.html
docs/index.md
docs/quickstart/google_colab.md

Use git colab instead of google drive colab.

Update colab links to use repo colab

---

nerfstudio/configs/base_config.py

Don't add relative paths to experiment name

---

nerfstudio/model_components/renderers.py
nerfstudio/models/instant_ngp.py
tests/model_components/test_renderers.py

Produces cleaner depths for meshing.

Add median depth calculation

---

nerfstudio/cameras/cameras.py
nerfstudio/data/datamanagers.py
nerfstudio/data/dataparsers/base_dataparser.py
nerfstudio/data/dataparsers/dnerf_dataparser.py

This adds the ability to actually load the D-NeRF dataset, which another PR adds. This technically should be merged after that one, but they are independent. It also mostly is the same as `BlenderDataParserConfig` so I'm not sure if they should be merged together.

DNeRF Data Parser

---

nerfstudio/viewer/app/src/index.scss
nerfstudio/viewer/app/src/modules/RenderModal/RenderModal.jsx
nerfstudio/viewer/app/src/modules/RenderModal/index.jsx
nerfstudio/viewer/app/src/modules/SidePanel/CameraPanel/CameraPanel.jsx

Add additional documentation for rendering.

Update render UI

---

nerfstudio/data/dataparsers/instant_ngp_dataparser.py

Fix bug in implementation.
closes #912

Use tan instead of tanh

---

docs/quickstart/custom_dataset.md
scripts/process_data.py

Allow specifying colmap path

---

nerfstudio/viewer/app/src/modules/SidePanel/CameraPanel/CameraPanel.jsx

3D Viewer Displays cameras' Chosen Names

---

nerfstudio/viewer/app/src/index.scss
nerfstudio/viewer/app/src/modules/Banner/Banner.jsx
nerfstudio/viewer/app/src/modules/LandingModal/LandingModal.jsx
nerfstudio/viewer/app/src/modules/ViewportControlsModal/ViewportControlsModal.jsx
nerfstudio/viewer/app/src/modules/ViewportControlsModal/index.jsx

We have received a number of questions about how to control the camera. Hopefully this will help.

Add viewport controls help modal

---

nerfstudio/field_components/mlp.py

@kevinddchen noticed our MLP wasn't applying its output activation.

Missing mlp output activation

---

nerfstudio/data/datamanagers/__init__.py
nerfstudio/data/datamanagers/base_datamanager.py
nerfstudio/data/datamanagers/semantic_datamanager.py
nerfstudio/data/datasets/__init__.py
nerfstudio/data/datasets/base_dataset.py
nerfstudio/data/datasets/semantic_dataset.py

Add missing __init__.py files

---

nerfstudio/viewer/app/src/modules/Scene/Scene.jsx

Currently it the viewer zoom is too fast. This pr decreases the sensitivity.

Update viewer zoom sensitivity

---

nerfstudio/viewer/app/src/modules/WebSocket/WebSocket.jsx
nerfstudio/viewer/app/src/modules/WebSocketUrlField.jsx

Dont crash on invalid websocket

---

docs/developer_guides/viewer/viewer_overview.md

Update viewer docs

---

scripts/render.py

Remove unimplemented interp render option

---

nerfstudio/configs/base_config.py

Warnings are tricking up from using LPIPS. Silencing them for now.

Filter torchvision warnings

---

.github/workflows/core_code_checks.yml
nerfstudio/data/datamanagers/base_datamanager.py
nerfstudio/engine/trainer.py
nerfstudio/pipelines/base_pipeline.py
nerfstudio/pipelines/dynamic_batch.py
nerfstudio/utils/eval_utils.py
pyproject.toml

Some recent changes break when using python 3.7. Fix those changes and update tests to target 3.7

Fix python 3.7 support

---

nerfstudio/model_components/scene_colliders.py

currently only 1 but I'll scan for some more

Small Typos

---

nerfstudio/configs/method_configs.py
nerfstudio/models/base_model.py
nerfstudio/models/tensorf.py
nerfstudio/models/vanilla_nerf.py

The `VanillaModelConfig` should not exist in `base_model.py`

Cleanup configs

---

nerfstudio/viewer/app/src/modules/Scene/Scene.jsx

The arrow key translation currently moves pretty quickly. This PR decreases the speed.

Update viewer sensitivity

---

nerfstudio/data/dataparsers/nuscenes_dataparser.py
nerfstudio/process_data/__init__.py
nerfstudio/process_data/colmap_utils.py
nerfstudio/process_data/insta360_utils.py
nerfstudio/process_data/polycam_utils.py
nerfstudio/process_data/process_data_utils.py
nerfstudio/process_data/record3d_utils.py
nerfstudio/utils/rich_utils.py
nerfstudio/utils/scripts.py
scripts/process_data.py

Process data script was getting a bit unwieldy. This PR splits it into multiple files. This is purely a refactor, there are no changes in the logic.

Refactor process data

---

README.md
docs/quickstart/custom_dataset.md

Add metashape input data pipeline to documentation.

Add metashape to docs

---

nerfstudio/data/dataparsers/nerfstudio_dataparser.py

Dataparser would fail due to type mismatch.

Fix dataparser filename bug

---

nerfstudio/viewer/app/src/modules/WebRtcWindow/WebRtcWindow.jsx
nerfstudio/viewer/server/viewer_utils.py

Improve webrtc stability

---

nerfstudio/viewer/app/src/modules/SidePanel/CameraPanel/curve.js

Fix for #946, ended up being super simple

Pinched Looping Camera Path Fix

---

Dockerfile
README.md
docs/quickstart/installation.md

Added a Dockerfile to build docker image including all dependencies and nerfstudio itself.
Added description on how to use the docker image into the Readme.

Add Docker support

---

nerfstudio/viewer/app/package.json
nerfstudio/viewer/app/src/modules/ConfigPanel/ConfigPanel.jsx
nerfstudio/viewer/app/src/reducer.js
nerfstudio/viewer/server/viewer_utils.py

Adds a slider for render time in the viewer.
Only displays when the model has temporal distortion.
Is "render time" self-explanatory or is other wording better?

add render time in viewer

---

nerfstudio/process_data/polycam_utils.py

Use per frame polycam intrinsics when generating `transforms.json`.

Add per frame polycam intrinsics

---

nerfstudio/data/dataparsers/nerfstudio_dataparser.py

fixes this error:
File "C:\code\nerfstudio\nerfstudio\data\dataparsers\nerfstudio_dataparser.py", line 232, in _generate_dataparser_outputs
distortion_params = torch.stack(distort, dim=0)[idx_tensor]
IndexError: tensors used as indices must be long, byte or bool tensors

Fix IndexError runtime error

---

nerfstudio/configs/method_configs.py

Per discussion at https://github.com/nerfstudio-project/nerfstudio/issues/1072#issuecomment-1334644896
Temporary workaround for #1072

limit semantic-nerfw iterations to 30000

---

nerfstudio/viewer/app/package.json
nerfstudio/viewer/app/src/modules/SidePanel/ExportPanel/ExportPanel.jsx
nerfstudio/viewer/app/src/modules/SidePanel/ExportPanel/MeshSubPanel.jsx
nerfstudio/viewer/app/src/modules/SidePanel/ExportPanel/PointcloudSubPanel.jsx
scripts/exporter.py

Adding the UI for mesh export.

[WIP] Mesh export UI

---

nerfstudio/process_data/metashape_utils.py

Fix for when labels contain file extensions.

Metashape parsing fix

---

nerfstudio/configs/method_configs.py

Improving the defaults in mipnerf to avoid out of memory issues. See PR #1087 for more details.

Update mipnerf defaults

---

nerfstudio/viewer/app/src/modules/SidePanel/CameraPanel/CameraPanel.jsx
nerfstudio/viewer/server/utils.py

Fix crash on camera delete

---

nerfstudio/process_data/process_data_utils.py

Inform users if no images are found when using `ns-process-data`

Missing images error warning

---

colab/demo.ipynb

Speeding up installation time with a wheel. Had to go down to tinycudann v1.5, but should still work out fine.

Changed tinycudann to wheel to work with py3.8

---

nerfstudio/viewer/server/viewer_utils.py

There was a delay in the viewer when updating control panel properties. This PR removes that delay.

Immediately update viewer when output or cmap changes

---

nerfstudio/viewer/app/src/index.scss
nerfstudio/viewer/app/src/modules/SidePanel/CameraPanel/CameraPanel.jsx
nerfstudio/viewer/app/src/modules/SidePanel/CameraPanel/CameraPropPanel.jsx

To improve UI consistency this PR adds leva controls to the Render tab.

Update render ui to use leva

---

nerfstudio/viewer/app/src/index.scss
nerfstudio/viewer/app/src/modules/SidePanel/SidePanel.jsx
nerfstudio/viewer/app/src/modules/SidePanel/StatusPanel/StatusPanel.jsx
nerfstudio/viewer/app/src/modules/ViewerWindow/ViewerWindow.jsx
nerfstudio/viewer/app/src/themes/theme.ts

Now when you are in the render view, it hides the rest of the scene. This will be necessary when we support other camera model output types (since threejs only supports pinhole)

Update Render View logic

---

nerfstudio/data/datamanagers/base_datamanager.py
nerfstudio/pipelines/dynamic_batch.py

Fix dynamic batch logic during inference

---

scripts/render.py

This fixes a bug where rendering broke when using `downscale-factor`.

Fix downscaling and type errors

---

colab/demo.ipynb

Created using Colaboratory

---

nerfstudio/field_components/mlp.py

Fix typo in mlp.py

---

nerfstudio/configs/base_config.py

I just did what the title said, for issue #1112

Added ETA to base config for the event writer

---

README.md

Quick fix to the Quickstart instructions in `README.md`. 
See [issue #1222](https://github.com/nerfstudio-project/nerfstudio/issues/1222) for details.

Update Quickstart instructions to remove '--dataset' (#1222)

---

nerfstudio/pipelines/base_pipeline.py

If extra info is in the checkpoint state, the code will now still run without crashing.

Non-strict loading of checkpoints

---

docs/quickstart/data_conventions.md

Add details about per-frame intrinsics

Update transform.json docs

---

nerfstudio/configs/method_configs.py

setting tensorf default from wandb to viewer

---

nerfstudio/process_data/process_data_utils.py

CottageMiniature sample dataset was only downsampling first image correctly prior to this fix.
It would appear that trusting ffmpeg with `%05d` commands to process all images is unreliable.  There may be other areas where similar fixes are warranted.

downsample all images

---

nerfstudio/configs/base_config.py
nerfstudio/engine/trainer.py
nerfstudio/viewer/app/package.json
nerfstudio/viewer/app/src/modules/RenderModal/RenderModal.jsx
nerfstudio/viewer/app/src/modules/SidePanel/CameraPanel/CameraPanel.jsx
nerfstudio/viewer/app/src/modules/SidePanel/CameraPanel/CameraPropPanel.jsx
nerfstudio/viewer/app/src/reducer.js
nerfstudio/viewer/server/viewer_utils.py

PR for [https://github.com/nerfstudio-project/nerfstudio/issues/451](https://github.com/nerfstudio-project/nerfstudio/issues/451)
I basically just sent the path to the data directory with a websocket the same way that the config directory is passed.

Camera path

---

nerfstudio/data/datamanagers/base_datamanager.py
nerfstudio/data/dataparsers/dycheck_dataparser.py
nerfstudio/data/utils/data_utils.py

Dataparser for DyCheck (https://arxiv.org/abs/2210.13445) Dataset (`iphone` subset).

DyCheck dataset parser

---

nerfstudio/cameras/rays.py
nerfstudio/model_components/renderers.py
nerfstudio/viewer/app/package.json
nerfstudio/viewer/app/src/modules/ConfigPanel/ConfigPanel.jsx
nerfstudio/viewer/app/src/reducer.js
nerfstudio/viewer/server/viewer_utils.py

Allow users to modify background color when cropping

---

scripts/blender/nerfstudio_blender.py

Updated how the Blender add on calculates duration with frame steps and added the case when frame step size is 0.

Updated Blender add-on calculating duration

---

nerfstudio/cameras/cameras.py
nerfstudio/viewer/app/src/modules/ConfigPanel/ConfigPanel.jsx
nerfstudio/viewer/app/src/modules/SidePanel/CameraPanel/CameraPanel.jsx
nerfstudio/viewer/app/src/modules/ViewerWindow/ViewerWindow.jsx
scripts/render.py

The render script now works with crops, ex:
https://user-images.githubusercontent.com/3310961/214962460-c44a7713-0c80-46ee-8eb1-05188d657852.mp4

Enable rendering with crop

---

nerfstudio/viewer/app/src/index.scss
nerfstudio/viewer/app/src/modules/ConfigPanel/ConfigPanel.jsx
nerfstudio/viewer/app/src/modules/LoadPathModal/LoadPathModal.jsx
nerfstudio/viewer/app/src/modules/LoadPathModal/index.jsx
nerfstudio/viewer/app/src/modules/RenderModal/RenderModal.jsx
nerfstudio/viewer/app/src/modules/SidePanel/CameraPanel/CameraPanel.jsx
nerfstudio/viewer/app/src/reducer.js
nerfstudio/viewer/app/src/themes/theme.ts
nerfstudio/viewer/server/viewer_utils.py

New Load Path button now opens a modal where users can either load an existing path or upload a path.

Load path dropdown

---

nerfstudio/model_components/scene_colliders.py

Add option for sphere collision.

Add sphere collider

---

README.md

Explicitly require NVIDIA graphics cards in README

---

nerfstudio/cameras/cameras.py
nerfstudio/viewer/server/viewer_utils.py

Fixes bug from recent commit that stopped rending crops. Also adds a try/except to fallback to pytorch if nerfacc isn't working.

Fix crop robustness

---

pyproject.toml

As per discussion in https://github.com/nerfstudio-project/nerfstudio/pull/1277#issuecomment-1411151700

bump nerfacc to 0.3.4

---

nerfstudio/generative/__init__.py
nerfstudio/generative/stable_diffusion.py
pyproject.toml

This will make it easier to incorporate diffusion models into NeRF (ie dreamfusion).

Add Stable Diffusion helper code

---

nerfstudio/engine/trainer.py

This might also help with https://github.com/nerfstudio-project/nerfstudio/issues/873

add option to log training gradients

---

nerfstudio/utils/install_checks.py
scripts/downloads/download_data.py

Throw a warning to the user if `curl` is not installed.

Check if curl is installed

---

nerfstudio/viewer/app/package.json
nerfstudio/viewer/app/src/modules/ConfigPanel/ConfigPanel.jsx
nerfstudio/viewer/app/src/reducer.js
nerfstudio/viewer/server/viewer_utils.py

Improve viewer colormap choices

---

nerfstudio/generative/stable_diffusion.py
scripts/generative/trace_stable_diffusion.py

Allows for faster inference of stable diffusion.

Trace Stable Diffusion

---

nerfstudio/engine/trainer.py

This PR fixes a bug in `ns-train --help`.

Fix ns-train help

---

nerfstudio/cameras/rays.py
nerfstudio/engine/trainer.py
nerfstudio/fields/instant_ngp_field.py
nerfstudio/model_components/renderers.py
nerfstudio/utils/math.py
scripts/train.py

Fixed typos in:
- `nerfstudio/cameras/rays.py`
- `nerfstudio/engine/trainer.py`
- `nerfstudio/fields/instant_ngp_field.py`
- `nerfstudio/model_components/renderers.py`
- `nerfstudio/utils/math.py`
- `scripts/train.py`

Fix Multiple Typos

---

pyproject.toml

Downgrade nerfacc until https://github.com/nerfstudio-project/nerfstudio/issues/1405 is fixed.

Downgrade nerfacc to 0.3.3

---

nerfstudio/generative/stable_diffusion.py

Make SDS return loss and fix CFG calculation.

Update SDS loss

---

nerfstudio/models/instant_ngp.py
nerfstudio/models/mipnerf.py
nerfstudio/models/nerfacto.py
nerfstudio/models/nerfplayer_nerfacto.py
nerfstudio/models/nerfplayer_ngp.py
nerfstudio/models/semantic_nerfw.py
nerfstudio/models/tensorf.py
nerfstudio/models/vanilla_nerf.py

Change the expected data range of LPIPS module (`LearnedPerceptualImagePatchSimilarity`) from [-1, 1] to [0, 1] as mentioned in #1424

Fix LPIPS data range

---

nerfstudio/model_components/ray_samplers.py

Currently it is fixed to a piecewise sampler that works well with unbounded scenes. This PR add the ability to change the initial sample method.

Proposal network initial sampler

---

nerfstudio/models/depth_nerfacto.py

Fix depth nerfacto exporting

---

nerfstudio/cameras/camera_optimizers.py
nerfstudio/configs/experiment_config.py
nerfstudio/configs/method_configs.py
nerfstudio/engine/optimizers.py
nerfstudio/engine/schedulers.py
nerfstudio/models/tensorf.py

The schedulers code now uses the same structure that other classes use.

Refactor schedulers

---

nerfstudio/engine/schedulers.py

Add linear ramp. Clean up docs

Update exponential scheduler

---

nerfstudio/data/datamanagers/base_datamanager.py

Remove unintended changes from #1473

Fix datamanager

---

nerfstudio/process_data/process_data_utils.py

Fix relative argument

---

docs/developer_guides/pipelines/dataparsers.md
nerfstudio/data/dataparsers/nerfstudio_dataparser.py
nerfstudio/data/dataparsers/nuscenes_dataparser.py
nerfstudio/data/dataparsers/phototourism_dataparser.py

Rename train_split_percentage with train_split_fraction

---

pyproject.toml

Bump nerfacc to fix #1405 #1413 #1414. See nerfacc issue https://github.com/KAIR-BAIR/nerfacc/issues/156

bump nerfacc to 0.3.5

---

nerfstudio/pipelines/base_pipeline.py
tests/pipelines/test_vanilla_pipeline.py

I am very sorry to have introduced the bug in #1499 :( 
Please consider accepting this PR soon as it prevents people from restarting training from checkpoints.
This PR should fix the introduced bug and update the tests to cover it.

Fixes bug introduced in #1499 preventing load_from_checkpoint to work correctly 

---

docs/nerfology/methods/semantic_nerfw.md
nerfstudio/configs/method_configs.py
nerfstudio/data/datamanagers/base_datamanager.py
nerfstudio/data/dataparsers/sitcoms3d_dataparser.py
scripts/downloads/download_data.py

Rename friends dataset to sitcoms3d

---

nerfstudio/engine/callbacks.py
nerfstudio/engine/optimizers.py
nerfstudio/engine/schedulers.py
nerfstudio/engine/trainer.py

This PR aims to improve and add to the currently existing type hints in the `engine` submodule.

feat(engine): improve type hints

---

nerfstudio/process_data/process_data_utils.py

Otherwise ffmpeg error is a bit cryptic.

Check that video path is correct

---

nerfstudio/cameras/camera_utils.py
nerfstudio/cameras/cameras.py
nerfstudio/cameras/rays.py
nerfstudio/exporter/texture_utils.py
nerfstudio/exporter/tsdf_utils.py
nerfstudio/plugins/registry.py

Following up with work done in #1509, this PR aims to further improve and add to the currently existing type hints.

feat: improve type hints

---

nerfstudio/engine/optimizers.py

This PR only adds the weight_decay option to RAdam optimizer.

Add weight-decay option to RAdam optimizer

---

nerfstudio/configs/experiment_config.py
nerfstudio/data/datamanagers/base_datamanager.py
nerfstudio/engine/trainer.py
nerfstudio/pipelines/base_pipeline.py
scripts/train.py
scripts/viewer/run_viewer.py

Some datamanagers may not require a dataparser. This PR removes that dependency.

Remove dataparser dependency

---

nerfstudio/cameras/camera_utils.py

The issue #1530 could be potentially solved by this small patch.

Adding conversion to torch.float32 in get_interpolated_poses_many.

---

nerfstudio/exporter/exporter_utils.py

Switch to using double to get speedup - https://github.com/isl-org/Open3D/issues/1045

Speed up point cloud export

---

nerfstudio/data/dataparsers/scannet_dataparser.py

Fixing typos in pose orientation.

Fix minor scannet bug.

---

docs/quickstart/custom_dataset.md

Fixed percent crop typo

---

docs/quickstart/custom_dataset.md
nerfstudio/process_data/equirect_utils.py
nerfstudio/process_data/process_data_utils.py
scripts/process_data.py

- changed argument
- updated docs
- Added value error if crop values are less than 0 or more than 1

Changed percent-crop to crop-factor so it's less confusing

---

nerfstudio/viewer/server/viewer_utils.py

Currently if the regex check fails, the code will crash.

Remove regex for export path

---

nerfstudio/data/pixel_samplers.py

Issue with dynamic batch size. Fixed with override to PixelSampler method.

Patch Sampling bug fix

---

colab/demo.ipynb

Thanks to azua_23423333 on Discord for sharing the colmap installation speed-up!

Updated Colab to Python3.9 and added colmap install speedup.

---

nerfstudio/process_data/process_data_utils.py
scripts/process_data.py

https://github.com/nerfstudio-project/nerfstudio/issues/1595

Adding the crop code made for videos to images

---

pyproject.toml

Typeguard was recently updated and is currently breaking.

Fix the typeguard version

---

docs/quickstart/custom_dataset.md
nerfstudio/process_data/colmap_utils.py

Colmap would open for users running on local machines. This should fix that.

Prevent colmap from opening

---

nerfstudio/process_data/metashape_utils.py

- support multiple sensors
- support fisheye and equirectangular sensors
- support multiple components with transforms
- fix bug when image name has a '.' in it, excluding the prefix separator

improve metashape data import

---

nerfstudio/viewer/app/src/index.jsx
nerfstudio/viewer/app/src/modules/LoadPathModal/LoadPathModal.jsx
nerfstudio/viewer/app/src/modules/Scene/Scene.jsx
nerfstudio/viewer/app/src/modules/SidePanel/CameraPanel/CameraPanel.jsx
nerfstudio/viewer/app/src/modules/SidePanel/ExportPanel/ExportPanel.jsx
nerfstudio/viewer/app/src/modules/SidePanel/ExportPanel/MeshSubPanel.jsx
nerfstudio/viewer/app/src/modules/ViewerWindow/ViewerWindow.jsx
nerfstudio/viewer/app/src/subscriber.js
nerfstudio/viewer/server/viewer_utils.py

Clean code and resolve some web console errors.

misc viewer cleanup

---

nerfstudio/process_data/hloc_utils.py

Previous setting will easily go to oom

Update pixsfm with better param

---

nerfstudio/model_components/renderers.py
tests/model_components/test_renderers.py

revise the SH renderer and drop the unnecessary color prior(0.5)

Fix bug: sh render is not correct

---

nerfstudio/pipelines/base_pipeline.py
tests/pipelines/test_vanilla_pipeline.py

Hi,
This pull request can fix https://github.com/nerfstudio-project/nerfstudio/issues/1636, and will also allow the checkpoint from non-ddp training to be loaded in ddp mode.

fix checkpoint generated by ddp training cannot be loaded

---

nerfstudio/data/dataparsers/nerfstudio_dataparser.py

Update nerfstudio data defaults

---

nerfstudio/viewer/server/viewer_state.py
nerfstudio/viewer/viser/server.py

Switching host to`127.0.0.1`.
Fixes #1735

Update host address

---

docs/nerfology/methods/index.md
docs/nerfology/methods/lerf.md

Currently, what should be finished:
Remaining TODOS:
@kerrj

Add documentation for LERF

---

docs/quickstart/custom_dataset.md
scripts/process_data.py

Changed the "obscene mesh of human" wording and added `--crop-bottom [num]` arg to equal `--crop-factor 0.0 [num] 0.0 0.0`

Added docs wording change and also --crop-bottom

---

nerfstudio/viewer/app/src/modules/WebSocket/ViserWebSocket.tsx

The server will new automatically connect with the socket becomes open.

Automatically reconnect to server

---

nerfstudio/viewer/viser/messages.py

...to reflect that we can have multiple folders!

Fix folder labels type annotation

---

nerfstudio/utils/profiler.py

Fixes bug mentioned here: https://github.com/nerfstudio-project/nerfstudio/pull/1761#issuecomment-1521174215

Fix profiler for PyTorch 2.0

---

nerfstudio/viewer/app/package.json
nerfstudio/viewer/app/yarn.lock

Resolves dependabot security warning about yaml package.

force resolution of yaml for security

---

nerfstudio/process_data/base_converter_to_nerfstudio_dataset.py
nerfstudio/process_data/colmap_converter_to_nerfstudio_dataset.py
nerfstudio/process_data/images_to_nerstudio_dataset.py
nerfstudio/process_data/video_to_nerfstudio_dataset.py
scripts/process_data.py
tests/process_data/test_process_images.py

The classes to convert images and video to a NerfStudio dataset are moved to the main repo and refactor:
* Code duplications are removed
* Import of the class is now done from nerfstudio package instead of scripts

Refactor of image and video dataset conversion

---

scripts/viewer/sync_viser_message_defs.py

If the viewer messages change, the version number will be incremented to ensure that users connect to the correct version. Note that if two message updates are committed in the same day, the second merge needs to be manually updated.

Auto update viewer version

---

nerfstudio/viewer/app/package.json
nerfstudio/viewer/app/src/modules/WebSocket/ViserMessages.tsx
nerfstudio/viewer/app/src/modules/WebSocket/ViserWebSocket.tsx
nerfstudio/viewer/app/src/reducer.js
nerfstudio/viewer/server/render_state_machine.py
nerfstudio/viewer/viser/message_api.py
nerfstudio/viewer/viser/messages.py

Fix viewer meshing options

---

nerfstudio/engine/trainer.py

Quit training loop upon completion when viewer is not used.

Quit when not using viewer

---

nerfstudio/cameras/cameras.py
nerfstudio/utils/math.py

The speedup is negligible and not worth the complications in the implementation.

Remove nerfacc aabb

---

nerfstudio/viewer/app/src/modules/SidePanel/CameraPanel/CameraPanel.jsx

fix for https://github.com/nerfstudio-project/nerfstudio/issues/1845

CropParamsMessage

---

nerfstudio/data/datamanagers/base_datamanager.py

In my case, mask here is a Something like this: [[True], [True], [False]....].
Using "if mask" will cause this issue:
RuntimeError: Boolean value of Tensor with more than one value is ambiguous.

Fix mask bug

---

nerfstudio/scripts/render.py
nerfstudio/utils/colormaps.py
nerfstudio/viewer/app/src/themes/leva_theme.json
nerfstudio/viewer/server/control_panel.py
nerfstudio/viewer/server/render_state_machine.py
nerfstudio/viewer/server/viewer_state.py

Add split screen

---

nerfstudio/process_data/metashape_utils.py

If there is only 1 component, the 'components' tag is not present in the .xml file -> the variable `components` becomes `None` and not `iterable`. PR solves this problem. 
See the latest discussion started by `brycelynch#9743` in the troubleshooting channel.

fix metashape_to_json() if there is no 'components' tag in .xml

---

nerfstudio/viewer/app/src/modules/ConfigPanel/ConfigPanel.jsx
nerfstudio/viewer/app/src/themes/leva_theme.json
nerfstudio/viewer/server/control_panel.py
nerfstudio/viewer/server/viewer_elements.py
nerfstudio/viewer/viser/message_api.py

Add button groups to viewer

---

nerfstudio/cameras/camera_paths.py
nerfstudio/cameras/camera_utils.py
nerfstudio/cameras/cameras.py
nerfstudio/data/dataparsers/nerfstudio_dataparser.py
nerfstudio/fields/nerfplayer_nerfacto_field.py
nerfstudio/scripts/exporter.py
nerfstudio/scripts/render.py

Type fixes and cleanup

---

tests/field_components/test_temporal_grid.py

Disabling for now since loss is currently failing

Don't run temporal tv loss test

---

nerfstudio/configs/experiment_config.py
nerfstudio/engine/trainer.py
nerfstudio/utils/decorators.py
nerfstudio/viewer_beta/__init__.py
nerfstudio/viewer_beta/render_state_machine.py
nerfstudio/viewer_beta/utils.py
nerfstudio/viewer_beta/viewer_state.py
pyproject.toml

We will be developing a full viser viewer. The viewer will be accessible using `--vis viewer_beta`

Basic viser frontend

---

docs/developer_guides/new_methods.md

Fix custom dataparser docs

---

.devcontainer/devcontainer.json
.vscode/settings.json

Makes a few changes to better integrate with the ruff vscode extension.

style(ruff): provide better integration with ruff vscode extension

---

README.md
docs/index.md

Updating the citation for the ACM SIGGRAPH 2023 conference proceedings.

SIGGRAPH 2023 Citation Update

---

nerfstudio/data/dataparsers/base_dataparser.py

I found in my research that I needed some additional kwargs beyond "split" to generate dataparser outputs. Added kwargs as optional arguments.

Add kwargs to dataparser outputs

---

nerfstudio/data/dataparsers/scannet_dataparser.py

for issue :https://github.com/nerfstudio-project/nerfstudio/issues/2054
It fixes the camera poses loaded before.
For Scannet scene _scene0000_00_.
Before:
Fix:

fix for scannet dataset camera pose loading

---

nerfstudio/data/utils/data_utils.py

Update data_utils doc

---

nerfstudio/utils/math.py
tests/utils/test_math.py

Implements fix from #2081
Thanks @thetianshuhuang for finding the bug and providing the tests!

Fix spherical harmonics #2081

---

Dockerfile
docs/quickstart/installation.md

faced with the fact that a certain version of сuda was unavailable for me (11.8), so I set the parameter editable from outside

add `build-arg` cuda version to dockerfile

---

nerfstudio/field_components/encodings.py
nerfstudio/fields/density_fields.py

Default to tcnn

---

nerfstudio/engine/optimizers.py
nerfstudio/engine/trainer.py

- Add saving/loading scheduler state_dict to accommodate the training resumption on some methods with lr schedulers.

Add saving/loading scheduler state_dict

---

nerfstudio/process_data/process_data_utils.py

Supersedes #2229, closes both issues mentioned in #2230. Hopefully the last PR needed for this.

Remove superfluous -r1 (fix ffmpeg/colmap video)

---

docs/extensions/unreal_engine.md
nerfstudio/configs/external_methods.py
nerfstudio/configs/method_configs.py
tests/test_train.py

Volinga is now an external method, hosted in https://github.com/Volinga/volinga-model.

Moved Volinga as an external method

---

docs/developer_guides/new_methods.md

Added a small note to the template-nerfstudio repo for quickly registering new methods

template repository 

---

nerfstudio/cameras/camera_optimizers.py

In reference to the confusion brought up in #2323

Rename num_cameras to camera_indices 

---

nerfstudio/data/dataparsers/colmap_dataparser.py

Fix [this issue](https://github.com/nerfstudio-project/nerfstudio/issues/2329).

fix: ColmapDataParser downscaling images error.

---

README.md
docs/index.md

Adding a Nerfstudio feedback form to the readme and docs. The URL will be updated before merging.

Nerfstudio Feedback Form

---

nerfstudio/model_components/renderers.py

Fixes crop background color override

---

nerfstudio/data/dataparsers/colmap_dataparser.py

Rename COLMAP 3D point features

---

README.md
docs/developer_guides/debugging_tools/benchmarking.md
docs/developer_guides/pipelines/models.md
docs/developer_guides/viewer/custom_gui.md
docs/quickstart/first_nerf.md
nerfstudio/configs/experiment_config.py
nerfstudio/engine/trainer.py
nerfstudio/utils/decorators.py
nerfstudio/utils/writer.py
pyproject.toml

This Pull Request aims to Add Comet as a Logging/Experiment Management Tool. 
I created a [Colab](https://colab.research.google.com/drive/1RqIIr9feGBymPXyOQ1PgBih5w3ErHdza#scrollTo=9oyLHl8QfYwP) to test out this feature! 
Let me know if you guys have any questions! Happy to help

Add Comet Logging 

---

nerfstudio/engine/trainer.py
nerfstudio/models/nerfacto.py
nerfstudio/scripts/render.py
nerfstudio/viewer_beta/render_panel.py
nerfstudio/viewer_beta/viewer.py

Adds support for for rendering with oriented boxes in the new viewer.
https://github.com/nerfstudio-project/nerfstudio/assets/15806475/7e35c4e4-e433-44c1-b10e-8b5cea752b52

Render oriented crops in viewer beta

---

.github/workflows/doc.yml

Don't deploy docs from pull requests

---

nerfstudio/viewer_beta/control_panel.py
pyproject.toml

use .content flag of markdown to avoid flicker

Fix jitter viewer

---

README.md

Before: Small blue underlines between the buttons and badges.
After: Cleaned as expected.

Fix HTML render of README.md

---

nerfstudio/field_components/encodings.py

NeRFEncoding won't include input if using tcnn,got fixed

fix include_input for NeRFEncoding

---

Dockerfile
nerfstudio/process_data/colmap_converter_to_nerfstudio_dataset.py
nerfstudio/process_data/hloc_utils.py
nerfstudio/process_data/process_data_utils.py

This PR is just https://github.com/nerfstudio-project/nerfstudio/pull/2531/files, so all credits go to @Michael-Spleenlab, but it also includes the fixed Dockerfile comment, so we can merge this faster

Update hloc and add new matcher types

---

nerfstudio/cameras/cameras.py

The self.times was being computed twice in cameras.py in the same function which was unnecessary

Update cameras.py - removed duplicate lines

---

nerfstudio/viewer_beta/viewer.py
pyproject.toml

Pulling #2586 out of the splatting branch!

Fix large dataset (> 512 images) training in viewer_beta

---

nerfstudio/process_data/equirect_utils.py

https://github.com/nerfstudio-project/nerfstudio/pull/1446#issuecomment-1812115064

Added support for .tif and .tiff files in equirect utils

---

README.md
docs/quickstart/custom_dataset.md

* Adds easy support for new device types: OAK-D, RealSense and Azure Kinect, as well as an alternative pipeline for iOS (+ Android coming soon)
* Differences to other approaches: Uses VISLAM (with post-processing, unlike ARKit) instead of purely image-based methods to compute camera poses -> more robust especially with quick scans. No need to upload the data to a 3rdparty server for processing
ping @maturk

Add instructions for data collection and processing with Spectacular AI tools

---

nerfstudio/data/dataparsers/dycheck_dataparser.py

Not sure if depth is correct since I'm not sure what the 3rd dim is for, the code runs properly though. Resolves #2619

Fix dycheck depth and rgb rescale

---

docs/index.md
docs/nerfology/methods/igs2gs.md
docs/nerfology/methods/index.md
nerfstudio/configs/external_methods.py

Adding documentation for Instruct-GS2GS including its page and adding it to the list of external and 3rd party methods.

Adding docs for Instruct-GS2GS

---

pyproject.toml

For tone mapping fixes: https://github.com/nerfstudio-project/viser/pull/160

Bump viser

---

docs/extensions/blender_addon.md
docs/nerfology/methods/splat.md

Adding 3rd party viewers for splats and other edits to gs documentation.

Update documentation for 3DGS

---

nerfstudio/data/datamanagers/parallel_datamanager.py

Fix typo in parallel_datamanager.py

---

nerfstudio/data/datamanagers/full_images_datamanager.py

Fix mask shape for Fisheye624 cameras

---

README.md

This was for the legacy viewer!

Remove viewer build badge

---

nerfstudio/process_data/odm_utils.py
nerfstudio/scripts/process_data.py

Hello :wave:
this PR adds support for loading 3D points (useful for running `splatfacto`) from datasets imported from ODM.
Hope this can be useful to others.

Add support for loading 3D points with ODM data processor

---

nerfstudio/fields/nerfacto_field.py
nerfstudio/fields/nerfw_field.py

#2843
@brentyi  Implements suggested changes.

Fix #2843 - safer typing

---

pyproject.toml

Since we only upper-bound to suppress some type errors!

Upper-bound torch version for dev installs only

---

nerfstudio/data/datamanagers/parallel_datamanager.py

As it stands one cannot use a custom Dataset class in ParallelDatamanager. This handles that usecase in the same manner as VanillaDataManager and FullImagesDataManager

support generic TDataset in paralleldatamanager

---

nerfstudio/scripts/benchmarking/launch_train_blender.sh

This PR fixes the camera optimizer argument in benchmarking scripts after #2092.

Fix benchmarking script camera optimizer argument

---

nerfstudio/configs/method_configs.py
tests/test_train.py

-Added splatfacto-big which is just lower cull threshold and no culling after 15k steps
Those are the parameters I used for the splatfacto-big in the eval table

splatfacto-big

---

nerfstudio/scripts/datasets/process_project_aria.py

See Aria update here: https://facebookresearch.github.io/projectaria_tools/docs/ARK/sw_release_notes#project-aria-updates-aria-mobile-app-v140-and-changes-to-mps

Support new MPS filenames for Project Aria point clouds

---

pyproject.toml

Need to bump a new version for issues like: https://github.com/nerfstudio-project/nerfstudio/issues/3033

bump version to 1.0.3

---

docs/index.md
docs/nerfology/methods/index.md
docs/nerfology/methods/signerf.md
nerfstudio/configs/external_methods.py

Readme and installation guide for SIGNeRF in the Nerfstudio documentation

Added SIGNeRF to Nerfstudio methods 

---

nerfstudio/pipelines/base_pipeline.py

write eval combined images for diagnostics

---

nerfstudio/scripts/exporter.py
tests/scripts/test_exporter.py

GaussianSplats export: allow uint8 in ply

---

nerfstudio/process_data/polycam_utils.py
nerfstudio/scripts/process_data.py

Add a pointcloud export from polycam to process-data

---

docs/nerfology/methods/splat.md

Clarify flag name in docs/nerfology/methods/splat.md

---

nerfstudio/cameras/cameras.py

See https://github.com/nerfstudio-project/nerfstudio/issues/3135#issue-2290195083

Fix legacy tensor construction

---

nerfstudio/scripts/downloads/download_data.py

Skip over `__MACOSX` directory
Fixes https://github.com/nerfstudio-project/nerfstudio/issues/3160

Fix "poster" dataset extraction

---

pyproject.toml

Fixes cropbox dtype edge case in the viewer.

Bump viser to 0.2.3

---

nerfstudio/models/splatfacto.py

fix https://github.com/nerfstudio-project/gsplat/issues/268

fix color shape when sh_degree=0 in splatfacto

---

nerfstudio/data/dataparsers/scannet_dataparser.py

Reading the .ply file on scannet_dataparser.py is possible. Users can read .ply file's point cloud positions or point cloud positions+colors.

Added _load_3D_points to scannet_dataparser.py

---

nerfstudio/scripts/render.py

Allows rendering the appearance of specific training camera indices (for splatfactow).

Allows rendering the appearance of specific training camera indices

---

nerfstudio/engine/trainer.py
nerfstudio/viewer/viewer.py

Hi guys,
I tried to run generfacto and it crashes in current version. I fixed 2 little bugs.
Could someone have a look in it ?
thanks

fix bugs in generfacto, train_dataparser_outputs.save_dataparser_transform and viewer camera on cpu

---

pyproject.toml

Bump viser to 0.2.7

---

.github/workflows/build_docker_image.yml

Fix docker attestation fail on forked repo PRs

---

nerfstudio/cameras/camera_paths.py
nerfstudio/cameras/camera_utils.py

This PR addresses Issue #3418, where the ns-render interpolate mode was unable to render 4D datasets.

add time interpolation support for ns-render interpolate

---

docs/nerfology/model_components/visualize_encoders.ipynb
nerfstudio/cameras/cameras.py
nerfstudio/data/datamanagers/full_images_datamanager.py
nerfstudio/data/dataparsers/dycheck_dataparser.py
nerfstudio/data/dataparsers/nerfstudio_dataparser.py
nerfstudio/data/dataparsers/nuscenes_dataparser.py
nerfstudio/data/datasets/base_dataset.py
nerfstudio/data/pixel_samplers.py
nerfstudio/data/utils/nerfstudio_collate.py
nerfstudio/engine/callbacks.py
nerfstudio/exporter/exporter_utils.py
nerfstudio/field_components/encodings.py
nerfstudio/fields/base_field.py
nerfstudio/model_components/ray_samplers.py
nerfstudio/models/base_surface_model.py
nerfstudio/models/tensorf.py
nerfstudio/pipelines/base_pipeline.py
nerfstudio/pipelines/dynamic_batch.py
nerfstudio/process_data/colmap_converter_to_nerfstudio_dataset.py
nerfstudio/process_data/polycam_utils.py
nerfstudio/process_data/process_data_utils.py
nerfstudio/scripts/downloads/download_data.py
nerfstudio/scripts/downloads/eyeful_tower.py
nerfstudio/scripts/render.py
nerfstudio/utils/comms.py
nerfstudio/utils/tensor_dataclass.py
nerfstudio/utils/writer.py
nerfstudio/viewer/viewer_elements.py
nerfstudio/viewer_legacy/server/viewer_state.py

Tests on new PRs are failing, this PR fixes the linting for new version of ruff.

rerun formatting with ruff 0.9.1

---

docs/extensions/maya_plugin.md
docs/index.md
nerfstudio/scripts/maya/nerfplugin_maya.py

adding Maya plugin + docs (remaking pull request to resolve issues with formatting)

Maya plugin and documentation

---

nerfstudio/data/datamanagers/full_images_datamanager.py

Removing an unnecessary print statement in https://github.com/nerfstudio-project/nerfstudio/pull/3604/ that was overlooked!

Removing unnecessary print statement
