nerfstudio-project/nerfstudio

nerfstudio/viewer/app/src/modules/SidePanel/CameraPanel/CameraPanel.jsx
Just fixing two corner cases I noticed:
1. If you press the "next frame" button when there are no cameras added, the slider currently goes negative
1. If you press the "prev frame" button after adding two cameras with the slider at 0, the viewer currently crashes
=> Fix viewer slider stepping past min/max limits

nerfstudio/viewer/server/viewer_utils.py
Remove logging in terminal for connecting to localhost. This is no longer necessary as users do not host the viewer.
=> Remove outdated viewer logging

docs/quickstart/first_nerf.md, nerfstudio/configs/method_configs.py, pyproject.toml, scripts/train.py
Just released `tyro` 0.3.23, which does some more aggressive caching and reduces the config overhead significantly. On my machine, parsing the full config library now takes ~0.15 seconds each time the `ns-train` script is run (down from ~0.45).
It's dramatically lower for the other scripts. (on the order of 1e-4 seconds)
A few changes:
- Bumped `tyro` dependency.
- Removed ANSI sequences from subcommand helptext. (these are unfortunately no longer supported)
- Copied the install scripts walkthrough from the docs to the help message + made some minor typo fixes and edits.
=> Reduced `tyro` overhead + helptext formatting

nerfstudio/model_components/ray_samplers.py, nerfstudio/model_components/renderers.py, nerfstudio/models/instant_ngp.py, pyproject.toml
- Bump nerfacc version to 0.2.0
- Fix depth visualization when the samples is packed.
NerfAcc 0.2.0 v.s. 0.1.3: Slight optimization on the library side. More util functions are supported. 
The huge performance improvements in NerfAcc 0.2.0 comes mainly from the better logic for occupancy grid updating. Not sure how to incorporate that which seems to need some refactor of the nerfstudio code. Left a comment in the code.
=> bump nerfacc to 0.2.0. bug fix for depth vis.

nerfstudio/viewer/app/src/modules/Scene/Scene.jsx, nerfstudio/viewer/app/src/modules/SidePanel/CameraPanel/CameraPanel.jsx
Addresses #695 , you can move the camera so that "up" looks correct and then press [Render->Reset Up Direction] and the grid will shift so that up matches the camera. Also adds a vector to display the local up direction once button is pressed.
=> Added up vector offset

nerfstudio/configs/method_configs.py, nerfstudio/models/nerfacto.py, nerfstudio/viewer/server/viewer_utils.py
Storing all of the eval sample info during eval would cause spikes in memory. By only storing during training this PR is able to reduce memory usage 2x while also increasing the number of eval chunks by 2x.
=> Reduce memory usage of nerfacto model

nerfstudio/configs/base_config.py
When using `ns-train` as part of a pipeline, it's convenient for the output directory to be deterministic. This should be achievable by passing the `--timestamp` argument to `ns-train`, but that argument is currently being overwritten. This PR fixes the logic to respect a custom user-provided `--timestamp` value.
=> Respect custom timestamps passed to `ns-train`

pyproject.toml
1. `ns-install-cli` was formerly breaking on machines where `nerfstudio` was installed via PyPI.
2. Need a `py.typed` for type checking if folks are using `nerfstudio` as a library: https://blog.whtsky.me/tech/2021/dont-forget-py.typed-for-your-typed-python-package/
=> Fix tab completion for PyPI installs, add `py.typed`

nerfstudio/viewer/server/viewer_utils.py
When the viewer was paused and the program was terminated via ctrl+c, the terminal would hang. This PR fixes that bug.
=> Fix threading bug

nerfstudio/viewer/app/src/modules/Scene/Scene.jsx
Fixes for #788 and #789. Visibility updates are shallow, so scene objects often have stale visible booleans. This adds a simple traversal up the parent chain to check visibility
=> [VIEWER] Camera Select Bug Fixes

nerfstudio/model_components/losses.py
This PR aims at accelerating nerfacto with `nerfacc`.
First commit is about accelerating `inner_outer` with `torch.searchsorted`.
6m8s -> 5m46s
WIP.
=> General acceleration of nerfacto

nerfstudio/cameras/camera_utils.py, nerfstudio/data/dataparsers/nerfstudio_dataparser.py, nerfstudio/data/dataparsers/record3d_dataparser.py
Adding the following three options for the nerfstudio dataset:
`--orientation-method {pca, up, none}` (can now be `none`)
`--center-poses {bool}`
`--auto-scale-poses {bool}`
=> Add more controls for orienting poses

scripts/completions/install.py
It seems like #747 added a few lines for initializing zsh completions, but these commands will cause errors in bash (`autoload: command not found`, `compinit: command not found`, etc).
I just:
- Removed these lines from the bash install.
- Added a condition to only run `compinit` when needed. `compinit` is quite slow (often 100s of milliseconds), so it's nice to avoid running it if it's not needed.
- Made the completion uninstall process more general.
=> Fix completion install script for bash

scripts/downloads/download_data.py, scripts/process_data.py
Small fix. the `missing_ok` optional arg in `Path.unlink` is only for Python 3.8+, so this makes it compatible with 3.7.
=> Pathlib Python 3.7 Compatibility Fix

nerfstudio/data/dataparsers/nerfstudio_dataparser.py
Some COLMAP datasets have missing images, like [fox](https://github.com/NVlabs/instant-ngp/tree/master/data/nerf/fox). This PR fixes the logic so that missing images are correctly ignored.
Also included is a slight modification which should still work for all filesystems.
=> Fix skipping non-existent images

nerfstudio/models/semantic_nerfw.py
Seems that there has been an update to the property naming in the `NerfactoModelConfig` class, which wasn't propagated into `semantic_nerfw.py`.
The culprit was `num_proposal_network_iterations` changing to `num_proposal_iterations`.
=> Fix semantic NeRF config bug

nerfstudio/configs/base_config.py, nerfstudio/viewer/server/viewer_utils.py
When the number of training images is large, the viewer can lag trying to display it all. This PR sets the maximum to the number of images shown in the viewer to 512. This can be changed in the config.
This completes one of the items in #833.
=> Limit number of images in viewer

scripts/render.py
You can now switch between rendering images or video with `--output-format {images, video}
=> Add option to render frames

scripts/process_data.py
On linux having a parentheses in the ffmpeg call causes it to break. This PR removes the parentheses.
=> Fix ffmpeg call

nerfstudio/viewer/app/src/modules/SidePanel/CameraPanel/curve.js
The rotation matrices for the camera paths were not orthogonal and did not have a det=1. This would cause wierd jumping artifacts.
Before
https://user-images.githubusercontent.com/3310961/198920295-33c78e50-e6b4-406d-95dc-6b2aa766e95d.mov
After
https://user-images.githubusercontent.com/3310961/198920246-1ddeede7-0e33-4ffe-bd49-9d1de4203971.mov
=> Fix camera interpolation bug

nerfstudio/engine/trainer.py
`check_main_thread` would return None in non-main processes, causing the script to crash. We now make sure to call that function only on `local_rank==0`
=> Viewer visualization crashes when using DDP

scripts/process_data.py
Alert the user when COLMAP does a poor job finding poses.
=> Add more debug logs to data processing

nerfstudio/engine/trainer.py
Related to: https://github.com/nerfstudio-project/nerfstudio/pull/863
After training the `always_render` method relies on `viewer_state` to be not None, that's only True in the main process
=> Check main thread when always rendering.

nerfstudio/engine/trainer.py
If the viewer is open when rendering starts, the resolution will be very low due to skewed speed calculations. This PR delays these calculations until after a few iterations to avoid this issue.
=> Start viewer with more accurate speed calculation

nerfstudio/model_components/exporters.py, pyproject.toml, scripts/exporter.py
Pointclouds can now be exported from a trained nerf.
`ns-export pointcloud --load-config CONFIG --output-dir DIR`
=> Support exporting point clouds

nerfstudio/field_components/mlp.py
This fixes `activation` being applied on the last layer:
```
... -> linear -> `activation` -> `output_activation` -> (output tensor)
```
Also replacing tuple-lookup with set-lookup.
=> Do not apply activation for last MLP layer

nerfstudio/fields/nerfacto_field.py, nerfstudio/fields/nerfw_field.py, nerfstudio/fields/semantic_nerf_field.py, nerfstudio/fields/tensorf_field.py, nerfstudio/fields/vanilla_nerf_field.py
When using the MLP defaults it does not set the output activation. The current models assume a relu activation has been applied.
=> Add missing activation

nerfstudio/configs/base_config.py, nerfstudio/engine/trainer.py
Adding the flag `--viewer.quit-on-train-completion True` will kill the training process when it completes. By default it continues to run to allow viewer interactivity.
=> Add flag to kill training when complete

nerfstudio/data/datamanagers/base_datamanager.py, nerfstudio/data/datamanagers/semantic_datamanager.py, nerfstudio/data/datasets/base_dataset.py, nerfstudio/data/datasets/semantic_dataset.py, nerfstudio/data/utils/data_utils.py, nerfstudio/data/utils/dataloaders.py, nerfstudio/pipelines/base_pipeline.py, nerfstudio/viewer/server/viewer_utils.py
As discussed briefly in https://github.com/nerfstudio-project/nerfstudio/pull/957 - it seems like have downsample support in the base InputDataset could be beneficial. While colmap outputs images at multiple-resolutions this may not be the case for many other applications where there are images only stored at a single resolution. This allows us to load in data in the raw format and downsample once loaded to disk
=> Support downsample in dataset

nerfstudio/process_data/metashape_utils.py, scripts/process_data.py
Add new option to `ns-process-data` to take in camera poses from Metashape.
In Metashape export camera params as a `.xml` by going to `File > Export > Export Cameras`. Then run the process script using the following command
```
ns-process-data metashape --data {Folder of images} --xml {xml filepath} --output-dir {output directort}
```
=> Add Metashape support

nerfstudio/field_components/encodings.py, nerfstudio/fields/tensorf_field.py
Previously, SceneBox.get_normalized_positions() returned a value in 0,1. This was fine for InstantNGP and Nerfacto, which use these values directly in an MLP. For TensoRF though, this was an error because grid sample expects values in the range `[-1,1]`. Thus, I think only 1/4th of the encoding planes were actually being used, and half of the encoding lines were.
=> TensoRF bugfix: AABB normalized_positions to [-1, 1]

docs/quickstart/first_nerf.md, docs/quickstart/installation.md, docs/quickstart/viewer_quickstart.rst
Simplify getting started documentation for web docs.
=> Simplify documentation

scripts/render.py
When using `traj=="filename"` `camera_ray_bundle` is generated on the cpu and then moved to the gpu which can be slow.
=> create rays on device when rendering

nerfstudio/data/utils/dataloaders.py
Hi,
I noticed that the loading of the images is not implemented with threads.
Using threadpool with 4 threads improved the loading time for me by a factor of 2-3, when the images are located locally on the machine SSD. 
If the images are located on a network drive the the loading time is better by a factor of 3-4.
This is particularly important when there are many images in the dataset and the RAM memory is "limited" ( for me 400 images could not fitt in my 48 GB memory) and the user have to use num_images_to_sample_from and num_times_to_repeat_image fields. In this case the training becomes very IO intensive ( you keep loading images throughout the training).
Thanks
=> implemented threadpool mechanics when loading images

README.md, docs/quickstart/first_nerf.md
As pointed out in https://github.com/nerfstudio-project/nerfstudio/issues/979#issuecomment-1324723023
=> (minor) `--trainer.load_dir` => `--trainer.load-dir` in docs

nerfstudio/process_data/metashape_utils.py, scripts/process_data.py
Fix two metashape related bugs,
+ For large datasets, some image might be removed, the json converter did not take this into account
+ Some metashape camera are missing transform data. We now take that into account.
=> Handle missing metashape data

nerfstudio/fields/nerfacto_field.py, nerfstudio/models/nerfacto.py, nerfstudio/models/semantic_nerfw.py
Allows Nerfacto's hashmap to be configured.
I found that increasing these values can improve the visual quality (reduces blur). As such it would be nice to be able to tune these via the command line.
=> config nerfacto

pyproject.toml, scripts/process_data.py
When using the metashape data processing, it would fail if other non-image files were included in the directory.
=> Ignore non-image files in ns-process-data

nerfstudio/process_data/insta360_utils.py, scripts/process_data.py
This adds support for the 2:1 aspect ratio single-file format used in some recording modes of Insta360 cameras (X3, normal video mode is confirmed, other modes unsure but possible).
Removed transpose from the ffmpeg command for fetching frames because I found it yielded better results.
I am not a python dev so please critique if I've made any horrible mistakes in this code!
Resolves #1019
=> Add support for insta360 single-file format

docs/developer_guides/debugging_tools/benchmarking.md, scripts/benchmarking/launch_eval_blender.sh, scripts/benchmarking/launch_train_blender.sh
- closes https://github.com/nerfstudio-project/nerfstudio/issues/1000
- see also https://github.com/nerfstudio-project/nerfstudio/issues/806
- launch_train_blender.sh:
- add -s option to launch a single job per GPU
- add -v option to use tensorboard instead of wandb
- set nerfacto options according to https://github.com/nerfstudio-project/nerfstudio/issues/806#issuecomment-1284327844
- use a single timestamp for all training jobs
- last GPU was ignored
- kill all subprocesses when script is terminated
- print the eval script command-line
-  launch_eval_blender.sh:
- add shebang
- add -s option to launch a single job per GPU
- last GPU was ignored
- kill all subprocesses when script is terminated
- update benchmarking doc
=> Fix benchmarking scripts

nerfstudio/configs/base_config.py, nerfstudio/viewer/server/viewer_utils.py
There seems to be an issue with some users if they are unable to connect to the TURN server. Seems to be related to - https://github.com/aiortc/aioice/issues/16
As a workaround, we now have the option to skip using openrelay servers suing the the command `--viewer.skip-openrelay`.
=> Allow users to skip using openrelay

scripts/process_data.py
Throw an error if user does not pass in an xml file into the `ns-process-data` metashape converter.
=> Check is metashape xml is present

nerfstudio/data/dataparsers/nerfstudio_dataparser.py
The nerfstudio `transforms.json` now allows per frame intrinsic values.
=> Add per frame intrinsic support to nerfstudio data

nerfstudio/utils/math.py
Found some bugs with torch spherical harmonics implementation. Using the `tcnn` implementation as reference: https://github.com/NVlabs/tiny-cuda-nn/blob/master/include/tiny-cuda-nn/encodings/spherical_harmonics.h
=> Fix torch spherical harmonics

nerfstudio/process_data/metashape_utils.py
Sometimes xml image labels have filetypes. We ignore them for consistency.
=> Fix metashape labels

nerfstudio/data/dataparsers/friends_dataparser.py
=> Make friends_dataparser path separator agnostic (fixes #1066)

nerfstudio/data/pixel_samplers.py
When using masks, I get the following error:
```
File "/home/hturki/miniconda3/envs/my-end/lib/python3.9/site-packages/nerfstudio/data/pixel_samplers.py", line 51, in <dictcomp>
collated_batch = {key: value[c, y, x] for key, value in batch.items() if key != "image_idx" and value is not None}
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)
```
printing the keys and devices in my batch, I see:
```
image_idx cuda:0
image cpu
mask cuda:0
``` 
Not sure if this fix is the most elegant solution
=> Fix device mismatch error when using masks

nerfstudio/cameras/cameras.py, nerfstudio/viewer/server/viewer_utils.py
Hi there!
I realized there are two bugs while working on `dnerf`.
First one is about training, caused by an incorrect shape of times tensor.
Second one is about the viewer. `times` return as zero when first connected to `viewer` and prevent entering the if clause.
Below two changes fixes it.
Thanks
=> Dnerf viewer and training fix

scripts/completions/install.py
I'm curious about the root cause of #1056, but it's difficult to debug without a useful error message.
To test this change, I slid an `assert False` into `scripts/render.py`:
Old error message just says that the subprocess failed:
New error message tells us why:
=> More informative completion install error messages

nerfstudio/field_components/encodings.py
Would like to compute the second derivative when using the tcnn hashgrid encoding as described in https://github.com/NVlabs/tiny-cuda-nn/issues/185.
=> Interpolation config for tcnn hashgrid

docs/quickstart/installation.md
Just a typo fix about 'get docker'.
=> 'get docker' typo

nerfstudio/viewer/server/viewer_utils.py
Implements max resolution rendering when not moving or training, in the spirit of #883.
=> Use max resolution when not moving or training

nerfstudio/cameras/camera_utils.py
When using auto_orient_and_center_poses with method="none" the returned pose is 4x4 (contrary to up and pca) which triggers an assertion error later. This modification solves it.
=> Bug correction auto_orient_and_center_poses

nerfstudio/fields/nerfacto_field.py, nerfstudio/models/nerfacto.py
Multiple users have reported that bumping the `max_res` value in the nerfacto model improves the quality (without increasing computation or memory). This PR updates the default.
=> Bump max res default

colab/demo.ipynb
This is a temporary fix. I couldn't get the wheel to work so installing from the pytorch bindings on git. Slightly slower installation now.
=> Colab working with Python3.8

nerfstudio/data/pixel_samplers.py
After fixing this bug, the training iter time improves from `600ms` to `30ms`.
[Info]
GPU: 3090
torch: 1.12.1+cu113
nerfacc: 0.2.1
nerfstudio: 0.1.12 (commit 90447ab)
=> Fix slow training issue when using mask

README.md, nerfstudio/configs/method_configs.py, nerfstudio/data/dataparsers/instant_ngp_dataparser.py, nerfstudio/data/dataparsers/nerfstudio_dataparser.py, nerfstudio/model_components/ray_samplers.py, nerfstudio/models/instant_ngp.py, scripts/benchmarking/launch_train_blender.sh, tests/test_train.py
Hi,
@tancik , as we discussed in #1099 , I inerested a new method based on instant-ngp (instant-ngp-boudned) that is designated for  bounded scenes.
I tried to tackle several problems in this Fork:
1. evaluation of instant-ngp-bounded on blender data set (using the benchmarking scripts)  looks way better (PSNR ranges 31-36 db)
2.  bounded real scene looks better and GUI looks similar to instant-ngp ( black background)
3. crashing bug in instant-ngp in cased of small aabb of size 1.
4. instant-ngp and nerfstudio data-parsers  can now handle any transformation file  instead of hardcoded transforms.json .
i.e --data directoy/my_trans_file.json . (backward compatible with plain directory)
There are several open issues and problems  that I encountered with thatI  want to open:
1. ignore …
=> instant-ngp-bounded model

nerfstudio/data/datamanagers/base_datamanager.py, nerfstudio/data/datamanagers/semantic_datamanager.py, nerfstudio/data/dataparsers/base_dataparser.py
=> Fix datamanager dataparser_outputs

nerfstudio/field_components/spatial_distortions.py
I'm finding the `torch.where` version of this function is about 2.5x faster and more readable.
```python
import torch
x = torch.randn(2048, 3, device='cuda')
def contract1(x, order):
mag = torch.linalg.norm(x, ord=order, dim=-1)
mask = mag >= 1
x_new = x.clone()
x_new[mask] = (2 - (1 / mag[mask][..., None])) * (x[mask] / mag[mask][..., None])
return x_new
def contract2(x, order):
mag = torch.linalg.norm(x, ord=order, dim=-1)[..., None]
return torch.where(mag < 1, x, (2 - (1 / mag)) * (x / mag))
assert torch.allclose(contract1(x, float('inf')), contract2(x, float('inf')))
```
```python
>>> %timeit contract1(x, float('inf')); torch.cuda.synchronize();
249 µs ± 10.4 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
```
```python
>>>%timeit contract2(x, float('inf')); …
```
=> Use `torch.where` for faster contract

nerfstudio/cameras/camera_paths.py, nerfstudio/cameras/cameras.py, nerfstudio/viewer/app/package.json, nerfstudio/viewer/app/src/modules/SidePanel/CameraPanel/CameraPanel.jsx, nerfstudio/viewer/app/src/modules/SidePanel/CameraPanel/CameraPropPanel.jsx, nerfstudio/viewer/app/src/modules/ViewerWindow/ViewerWindow.jsx, nerfstudio/viewer/app/src/reducer.js, nerfstudio/viewer/server/utils.py, nerfstudio/viewer/server/viewer_utils.py
In viewer add support for rendering with a fisheye and equirectangular camera.
Fisheye:
Equirectangular:
=> Support non-pinhole rendering

docs/reference/contributing.md
In the docs [contributing page](https://docs.nerf.studio/en/latest/reference/contributing.html), the discord link seems to be invalid (as reported by Discord)
However, the one in the README.md seems to work. So I copypasted the same link to the docs, too.
=> Fix Discord link in the docs

scripts/render.py
=> when camera_type is equirectangular, add spherical metadata to rendered video

nerfstudio/data/datasets/base_dataset.py
Some datasets may only be grayscale. In that case, it is easiest to simply convert them into RGB.
=> Support grayscale-only images in dataset

nerfstudio/data/pixel_samplers.py
moved collate methods as class methods, so sampling is only thing changed.
This is useful for future pixel sampling updates, as you don't need to write a whole new collate method if the only thing changing is the pixel sampling method.
=> PixelSampler refactor

nerfstudio/process_data/process_data_utils.py
Sometime ffmpeg would output 16 images when processing video to images. This only occurred when processing every frame. This would cause colmap to fail.
Fixes #1075
=> Force 8 bit output from ffmpeg

nerfstudio/model_components/ray_samplers.py, nerfstudio/models/instant_ngp.py, pyproject.toml
White -- nerfacc 0.3.x.
Blue -- nerfacc 0.2.x.
nerfacc 0.3.x uses CUB to accelerate the accumulation (both fwd and bwd) when available (cuda toolkit >= 11.5). Test rays / secs got ~10% speed up. For some reason the training speed is slightly slower with nerfacc 0.3.x, which needs to be further investigated.
Note the CUB acceleration is more noticeable when the #samples per ray is less, so the gap for test rays / secs got larger when converge. But it's unclear what's the reason of the slow down during training.
=> upgrade nerfacc to 0.3.x with CUB accel

nerfstudio/data/pixel_samplers.py
Fixing a check to see if the mask is None vs. a tensor.
=> Quick fix for mask None check

nerfstudio/data/datasets/base_dataset.py, nerfstudio/exporter/exporter_utils.py, scripts/exporter.py
The feature to export camera poses has already been requested by a few people (e.g. [issue-1051](https://github.com/nerfstudio-project/nerfstudio/issues/1051)).
I would also find this feature handy.
In this PR I implemented the exporter for camera poses. Currently, it exports the camera poses as two files: `transforms_train.json` and `transforms_eval.json` for train and eval poses.
the structure of these files is
```
[
{
"file_path": {image file path corresponding with this camera as in the original transforms.json},
"transform": {4x4 List of floats}
},
...
]
```
Even though we can export more information in the .json files, I find the these to be sufficient (at least for my use case). User can use the `file_path` to match the exported camera poses with the input camera poses.
I am happy …
=> Camera export

nerfstudio/viewer/app/src/modules/SidePanel/CameraPanel/CameraPanel.jsx
I basically just passed in `slider_value` and `set_slider_value` as a prop to the `CameraList` so it can change the slider.
Fix for https://github.com/nerfstudio-project/nerfstudio/issues/931
=> Making camera selection on viewer persistent

nerfstudio/fields/instant_ngp_field.py
Added the new arguments to the end of the argument list because this would preserve compatibility with pre-existing code written using positional arguments. However, this argument order differs from that used in nerfacto.
=> Add hashmap size and num_levels to instant_ngp_field, issue 1158

nerfstudio/model_components/ray_samplers.py
fixed an exception bug when num samples is 0 , 
"IndexError tensors used as indices must be long, byte or bool tensors"
change type to long ( was float32)
=> fixed an exception bug in case of num_samples is 0

README.md
`ns-download-data nerfstudio --capture-name=vegetation` will give error:
```
usage: ns-download-data [-h] --dataset {blender,friends,nerfstudio,record3d}
[--capture-name {None,bww_entrance,campanile,desolation,dozer,library,poster,redwoods2,sf_street,storefront,vegetation}] [--save-dir PATH]
ns-download-data: error: the following arguments are required: --dataset
```
Thus adding `--dataset` to the command.
=> Added missing arg to ns-download-data command

nerfstudio/model_components/ray_generators.py
Right now image coords are being needlessly serialized as part of the checkpoint state dict
=> save image_coords as non-persistent buffer

nerfstudio/data/datasets/base_dataset.py, nerfstudio/data/utils/data_utils.py, nerfstudio/process_data/colmap_utils.py, nerfstudio/process_data/process_data_utils.py, scripts/process_data.py
Add circle and edge cropping options to `ns-process-data`. The goal is to make it easier to process extreme fisheye images. 
Note that this will add `masks` to the dataset which currently blow up the memory usage.
=> Add cropping options to data processing

pyproject.toml
It appears, based on today's build, that https://github.com/nerfstudio-project/nerfstudio/issues/765#issuecomment-1384792529 is still necessary.  This PR ensures that we do not select too new a version of cryptography, in order to avoid resulting problems.
=> Rollback cryptography to fully working version (pre-39; 38 works)

nerfstudio/field_components/cuda/__init__.py, nerfstudio/field_components/cuda/_backend.py, nerfstudio/field_components/cuda/csrc/include/temporal_gridencoder.h, nerfstudio/field_components/cuda/csrc/pybind.cu, nerfstudio/field_components/cuda/csrc/temporal_gridencoder.cu, nerfstudio/field_components/temporal_grid.py, tests/field_components/test_temporal_grid.py
Implemented the sliding window operation in NeRFPlayer. The module is named `TemporalGridEncoder`, which takes in an extra parameter `time` when doing interpolation on the saved multi-scale volume grids.
=> NeRFPlayer sliding window implementation

nerfstudio/process_data/process_data_utils.py
As per discussion at https://github.com/nerfstudio-project/nerfstudio/pull/1055#issuecomment-1397490704
=> use -noautorotate option to avoid discrepancies (fixes #1260)

docs/index.md, docs/quickstart/blender_addon.md, scripts/blender/nerfstudio_addon_1_0.py, scripts/blender/nerfstudio_blender.py
First version of blender addon python script located in scripts/blender and new documentation for the addon. The Blender addon is for importing or exporting a camera path for visual effects and compositing.
=> Blender addon script and documentation

nerfstudio/data/dataparsers/nerfstudio_dataparser.py
Hi, 
I found the bug in `nerfstudio_dataparser.py` when I was working on multiple cameras with different distortion parameters.
This PR should fix `nerfstudio_dataparser` to load distortion parameters from multiple cameras correctly.
Thanks,
=> Bug fix for loading cameras with different distortions in nerfstudio_dataparser

nerfstudio/utils/eval_utils.py
Proposed fix for [issue 1271](https://github.com/nerfstudio-project/nerfstudio/issues/1271). I was able to use `ns-render` again after this fix.
=> Add `step` argument in `eval_utils.py` to fix rendering bug.

nerfstudio/models/nerfacto.py
Tweaked first proposal network hashgrid resolution from 64 to 128, helps the disappearing effect on thin objects.
=> Increase max_res of first proposal network

nerfstudio/engine/trainer.py
The total train time metric was not being logged as `writer.write_out_storage()` was not being called.
It would have included the time the viewer was open until the user killed the process which probably isn't what we want as well.
Metric now logged in wandb
Thanks for the great project and support on discord by the way!
=> Fix total train time metric logging

nerfstudio/process_data/polycam_utils.py, nerfstudio/process_data/process_data_utils.py, scripts/process_data.py
I was working on loading the LiDAR data from the polycam app by adding an option to the `ns-process-data polycam` interface. The API is as follows:
`ns-process-data polycam --use-depth --data 8ene,6-17p. m.-poly/ --output-dir output_data`
It searches in the keyframes folder for the depth data, scales it to match the RGB dimensions and adds it to the transforms.json. Is this still relevant with the recent [depth supervision pull request](https://github.com/nerfstudio-project/nerfstudio/pull/1173)?
=> Depth data loading for Polycam LiDAR data

nerfstudio/process_data/realitycapture_utils.py
I had practical situations when exported data from Reality Capture was not consistent. The number of cameras exported in CSV file was higher than the number of images on a very big dataset. This can be related to Reality Capture project settings and export options. CSV file and source images were exported separately. 
This situation gives an error with ns-process-data
These changes fix the issue with missing images in the Reality Capture data.
=> Fix the issue with missing images in the Reality Capture data.

nerfstudio/process_data/insta360_utils.py
Using bracket's in this situation causing syntax errors:
/bin/sh: 1: Syntax error: "(" unexpected
=> Remove bracket from ffmpeg command's crop filter

scripts/texture.py
@tancik Before this fix, using `scripts/texture.py` to texture an existing mesh will give an error: `TypeError: unsupported operand type(s) for /`.
This is due to the inconsistent argument order when calling `texture_utils.export_textured_mesh` from `scripts/texture.py`. The arguments `self.px_per_uv_triangle` and `self.output_dir` should be swapped.
=> Corrected the order of texture arguments

nerfstudio/configs/method_configs.py, nerfstudio/field_components/cuda/_backend.py, nerfstudio/field_components/temporal_grid.py, nerfstudio/fields/nerfplayer_nerfacto_field.py, nerfstudio/fields/nerfplayer_ngp_field.py, nerfstudio/model_components/ray_samplers.py, nerfstudio/models/nerfplayer_nerfacto.py, nerfstudio/models/nerfplayer_ngp.py, nerfstudio/viewer/server/viewer_utils.py, tests/test_train.py
NeRFPlayer implementation with `instant-ngp-bounded` and `nerfacto` model
Examples:
With `nerfacto` as the base model
With `instant-ngp-bounded` as the base model
=> nerfplayer with ngp and nerfacto

nerfstudio/viewer/server/viewer_utils.py
currently errors and ends training if datapath/camera_path doesn't exist. should still be able to load a path without erroring with this check.
=> adding check if camera_path_dir exists

Dockerfile, docs/quickstart/installation.md
Added the most common CUDA architectures to the Dockerfile as well as the docker image found at https://hub.docker.com/r/dromni/nerfstudio/tags
Also improved the description in the docs.
Now the following CUDA architectures should work:
GPU | CUDA arch
-- | --
H100 | 90
40X0 | 89
30X0 | 86
A100 | 80
20X0 | 75 
TITAN V / V100 | 70
10X0 / TITAN Xp | 61
9X0 | 52
K80 | 37
Fixes #1317
Fixes #1056
Fixes #1168
=> [Fix] Docker not supporting older CUDA architectures

nerfstudio/cameras/cameras.py, nerfstudio/utils/math.py
Speed up pytorch implementation ~3x and add logic to use nerfacc if available
=> Cleanup aabb intersection logic

nerfstudio/engine/optimizers.py
I've found that this makes training more stable in certain cases, especially when using high learning rates
=> Add support for gradient clipping

nerfstudio/viewer/server/viewer_utils.py
All of the model outputs were being moved to the CPU even though they are never used. This also means that the colormap code was operating on CPU instead of GPU. This PR should increase the speed of the viewer.
=> Dont move viewer outputs to cpu

nerfstudio/viewer/server/viewer_utils.py
Sometime the viewer would get into a weird state at the beginning of training if the initial render resolution is too low. This causes the GPU to be inefficient which then leads to a bad estimate of rendering speed. This in turn causes it to render in lower resolution leading to a feedback loop.
=> Set min render value for viewer

nerfstudio/configs/base_config.py, nerfstudio/viewer/server/utils.py, nerfstudio/viewer/server/viewer_utils.py
=> New config parameter --viewer.codec defaults to VP8, but allows H264

nerfstudio/process_data/process_data_utils.py, scripts/process_data.py
Fixes #1346 .
Confirmed on Windows 10 for `ns-process-data` `images` and `video` with spaces in filename.
Unable to test all processing options though.
=> double-quote filenames in process-data commands so that on Windows, paths with spaces don't fail

nerfstudio/process_data/polycam_utils.py
Hi,
I just changed the name in the transforms.json to be consistent with https://github.com/nerfstudio-project/nerfstudio/pull/1173
=> Consistent naming for depth maps in Polycam

nerfstudio/process_data/metashape_utils.py
This fix allows loading Metashape XML files which
contain an additional uncalibrated sensor.
Metashape XML format keeps unmatched images but
assignes a dummy sensor to them. The sensor has
no calibration data.
=> Handle uncalibrated Metashape sensor

nerfstudio/configs/base_config.py, nerfstudio/viewer/server/viewer_utils.py
If running local server instance, avoid using relays to communicate with the viewer.
=> add viewer.local config property when viewing local instance

nerfstudio/process_data/colmap_utils.py, nerfstudio/process_data/process_data_utils.py, scripts/process_data.py
This PR implements the following:
- Additional flag --skip-images for ns-process-data, which skips copying and downscaling of images. The typical use case is if the user already downscaled the images and wants to run just COLMAP
- Additional parameter --colmap-model-path can be used with --skip-colmap. It allows specifying the path to the COLMAP model as opposed to always using "colmap/sparse/0"
- Fixes a bug with --skip-colmap. When --skip-colmap is used with an existing COLMAP model, the filenames are not renamed (but they are renamed when they are copied and downscaled). This makes the resulting transforms.json contain invalid paths.
NOTE: I accidentally closed PR #1366. This PR contains the same changes.
=> Improve ns-process-data images when using existing COLMAP model

nerfstudio/model_components/losses.py, nerfstudio/models/depth_nerfacto.py
In nerfstudio, the losses for depth don't support sparse depth maps.  
1. Modified `ds_nerf_depth_loss`, `urban_radiance_field_depth_loss` in `losses.py`.
2. Modified the way of computing `depth_mse` in eval. 
3. Fixed typo `Depht` -> `Depth`.
Train `depth-nerfacto` with the `Replica` Dataset using only two views with sparse depth supervision (randomly masking out 90% of the depth map). left: groundtruth sparse depth map. right: predicted dense depth map. Results below are generated using `ds_nerf_depth_loss`.
=> Add support for sparse depth maps

nerfstudio/data/dataparsers/instant_ngp_dataparser.py
This PR adds the support for instant-ngp "is_fisheye" flag in the transforms.json file.
=> Add support for is_fisheye flag in ingp transforms.json

scripts/completions/install.py
This PR implements the following:
- All entrypoints are automatically registered for ns-install-cli completions
- ns-install-cli detects conda environment and instead of putting the activation scripts to bashrc or zshrc it uses the activation scripts of the conda environment.
=> Improve ns-install-cli

nerfstudio/exporter/exporter_utils.py, nerfstudio/models/nerfplayer_nerfacto.py
We have started using the NormalsShader for displaying normals, this shifts the normals between [0,1] which breaks the mesh export. This PR updates the exporter to assume [0,1] values.
=> Fix mesh export normals

nerfstudio/process_data/colmap_utils.py
An introduced bug would cause incorrect `transforms.json` files if colmap did not match all of the images as the `filename_map` would be incorrect.
This fix reverts to existing behavior. However this fix will break the functionality introduced in #1371
FYI - @jkulhanek
=> Fix colmap bug when not all images are matched

nerfstudio/configs/experiment_config.py, nerfstudio/engine/trainer.py
Allow users to use wandb or tensorboard at the same time as the viewer.
=> Enable viewer with eval

.devcontainer/docker-compose.yml, Dockerfile, docs/quickstart/installation.md
- Added hloc together with pycolmap to the Dockerfile (as it is already in dromni/nerfstudio:0.1.18)
- Updated docker image version in dev-container and docs.
- Added more documentation for docker usage.
=> [Update] Add hloc to Dockerfile, bump version of docker image in dev-container, improve docs

nerfstudio/process_data/colmap_utils.py, nerfstudio/process_data/process_data_utils.py, scripts/process_data.py
This PR (hopefuly) fixes problems introduced in #1366 and partially fixed in ( #1454 ). I am sorry for the problems introduced by the first PR.
@tancik , can you please take a look? This should fix the problems in the original PR while adding back the functionality of (--skip-colmap).
=> ns-process-data: fix image renaming for the --skip-colmap case

nerfstudio/pipelines/base_pipeline.py, tests/pipelines/test_vanilla_pipeline.py
This PR enables models to handle load_state_dict calls. Therefore, model classes can easily remap keys and do some shape changes on the checkpoint tensors. Also, strict checkpoint validation is used for pipeline.model.
=> Call load_state_dict on model classes

nerfstudio/fields/density_fields.py, nerfstudio/fields/nerfacto_field.py, nerfstudio/models/nerfacto.py, scripts/benchmarking/launch_eval_blender.sh, scripts/benchmarking/launch_train_blender.sh
Train `nerfacto` model on the `nerf-synthetic` requires some fixes:
- disable scene contraction to the model.
- filter out samples that are outside of scene aabb. (zero density)
- disable distortion loss.
Commands to train:
``` bash
CUDA_VISIBLE_DEVICES=0 ns-train nerfacto --vis wandb --data="data/blender/lego/" --experiment-name="blender_lego" --relative-model-dir=nerfstudio_models/ --steps-per-save=0 --max-num-iterations=16500 --logging.local-writer.enable=False --logging.enable-profiler=False --pipeline.model.background-color white --pipeline.model.proposal-initial-sampler uniform --pipeline.model.near-plane 2. --pipeline.model.far-plane 6. --pipeline.datamanager.camera-optimizer.mode off --pipeline.model.use-average-appearance-embedding False --pipeline.model.distortion-loss-mult 0 …
```
=> fixes for nerf synthetic dataset

nerfstudio/configs/experiment_config.py, nerfstudio/viewer/server/viewer_utils.py
If a users specified the dataset using `.../transforms.json` the model would train properly, but would save in the wrong place and the camera path logic would also fail. The PR strips the `transform.json` to avoid these issues.
=> Fix logic when using filename datasets

nerfstudio/cameras/camera_paths.py, nerfstudio/cameras/camera_utils.py, scripts/render.py
This PR extends possibility of ns-render utility to render the data using already available camera poses. It is helpful when working with large datasets (ScanNet, ARKitScenes) as well as HPC clusters where computational nodes are not connected to the internet.
=> Extending ns-render to support loop rendering using interpolated cameras

nerfstudio/data/datamanagers/base_datamanager.py, nerfstudio/data/dataparsers/arkitscenes_dataparser.py, nerfstudio/data/dataparsers/scannet_dataparser.py
This PR adds dataparsers that allow working with ScanNet and ARKitScenes datasets out of box.
Bellow I attach results obtained by running `ns-train nerfacto arkit-data`:
https://user-images.githubusercontent.com/38923619/221418322-f5f64f15-12f8-4188-a36b-2ea75a2fe960.mp4
And results obtained by running `ns-train nerfacto scannet-data`:
https://user-images.githubusercontent.com/38923619/221418342-6c778d29-8333-455d-b4a3-b97eefc76ee7.mp4
=> Dataparsers for ScanNet and ARKitScenes

nerfstudio/model_components/renderers.py
The current SHRenderer does not apply the activation function correctly due to a typo. Now it's fixed.
=> Bug fix for SHRenderer()

nerfstudio/data/dataparsers/arkitscenes_dataparser.py
A quick fix of typo in the ARKitScenes dataparser.
=> Fix pose centering flag for ARKitScenes dataparser

scripts/process_data.py
This fixes `process_data.py` for case where depth is not used. There is breaking the data processing script for colmap here https://github.com/nerfstudio-project/nerfstudio/blob/258ee26983a1985610fcb8681db403a9c1b9d2fe/nerfstudio/process_data/colmap_utils.py#L448 since `{} is not None` evaluates to True.
=> Fixing data processing script when depth is not used

nerfstudio/engine/trainer.py
When using WandB or TensorBoard, Nerfstudio considers that evaluation is enabled and thus crashes if the evaluation dataset is empty.
I just added a check before performing an evaluation iteration to avoid that issue.
=> Fix crash when having no eval dataset and not using the viewer

nerfstudio/data/utils/dataloaders.py
If the dataset is large, or the GPU doesn't have a lot of memory, loading all of the data onto the GPU could cause OOM errors.
=> Avoid loading entire dataset on GPU

nerfstudio/fields/instant_ngp_field.py, nerfstudio/models/instant_ngp.py
This commit adds ability to parametrize Instant-NGP model with `log2-hashmap-size` and `max-res` and also computes `per_level_scale` variable https://github.com/nerfstudio-project/nerfstudio/blob/f3a2ea0c925c8956effdbe36ff70149d58f08025/nerfstudio/fields/instant_ngp_field.py#L100
dynamically as in `nerfacto` model.
=> Instant ngp args

docs/quickstart/installation.md
This fixes the instruction for the cuda-architecture specific Docker build.
=> Correct instructions for Docker build

scripts/exporter.py
Use the newer Open3D Tensor API to write pointclouds as float32, which are compatible with PCL (see https://github.com/isl-org/Open3D/issues/1633).
this also reduces the file size (almost by half)
fixes https://github.com/nerfstudio-project/nerfstudio/issues/1571
=> scripts/exporter.py: export PLY compatible with PCL

docs/developer_guides/pipelines/dataparsers.md, nerfstudio/cameras/camera_utils.py, nerfstudio/data/dataparsers/arkitscenes_dataparser.py, nerfstudio/data/dataparsers/nerfstudio_dataparser.py, nerfstudio/data/dataparsers/phototourism_dataparser.py, nerfstudio/data/dataparsers/scannet_dataparser.py, nerfstudio/data/dataparsers/sdfstudio_dataparser.py
This PR adds a better vertical direction estimation (named "vertical"), which should work in most cases, even when cameras are in a parallel (eg LLFF) configuration (except that in this configuration cameras should be looking horizontally).
It also adds a different centering method, more appropriate for inward-looking configurations, called "focus". The previous unnamed centering method is now called "poses"
Additionally, we fixed inconsistent naming of `auto_scale_poses` as `scale_poses` is a couple of DataParserConfig. 
**Note:** The authors of this PR are @f-dy (previously known as @devernay, but I had to create another account for work-related contributions) and @gilureta .
The existing orientation method, which is called "up", works by averaging the up vector (Y) of all cameras. It …
=> camera_utils: add "vertical" orientation and "focus" center methods

nerfstudio/data/dataparsers/nerfstudio_dataparser.py, nerfstudio/data/utils/colmap_parsing_utils.py, nerfstudio/process_data/colmap_utils.py, tests/process_data/test_process_images.py
This PR adds tests for `ns-process-data images`.
It fixes a bug introduced by #1586.
=> Adds ns-process-data images tests and fixes #1586

nerfstudio/fields/base_field.py, nerfstudio/fields/instant_ngp_field.py, nerfstudio/fields/nerfacto_field.py, nerfstudio/fields/nerfplayer_nerfacto_field.py, nerfstudio/fields/nerfplayer_ngp_field.py
This PR aims to move the `get_normalized_directions` function in the `base_field.py` file instead of separately defining it in various other scripts.
=> feat(fields): create common `get_normalized_directions` fn

nerfstudio/configs/method_configs.py, nerfstudio/models/tensorf.py
Sampling bug fixed. ~28k rays/sec -> ~170k rays/sec. Seems like expected performance level--faster than nerfacto for me. Don't understand why tests are failing if y'all have any ideas.
New TensoRF (left) vs. Old TensoRf (right)
=> TensoRF go brrrrrrr

nerfstudio/utils/writer.py
When running various experiments, using the "experiment name" is quite useful for tracking with Weights and Biases, but it quickly becomes a mess with the random names.
This small PR sets the name of each run to the timestamp of the run to more easily identify them from the website.
This way, one can easily distinguish between runs within an experiment by using custom timestamps.
=> Use the run timestamp as run name on WandB

nerfstudio/process_data/process_data_utils.py
This PR is meant to fix Issue #1644.
Previously, the `-vf` arg was always added to the command regardless of whether there was a video filter to add or not. This PR changes this so that the `-vf` arg is only added if the `crop_cmd` is not empty (`""`).
Before making this change locally, I hit the error described in issue #1644. After making these changes, I have been able to run `ns-process-data video ...` as expected.
=> Fixed incorrect ffmpeg command construction

nerfstudio/data/dataparsers/nerfosr_dataparser.py
Fixing a typo for the nerf-osr validation set, 'split' was changed to 'validation' to match nerf-osr file structure but was checking for 'val' in the if statement.
=> Typo in nerfosr validation set

nerfstudio/configs/base_config.py, nerfstudio/viewer/server/viewer_utils.py
#1579 removed WebRTC from the viewer in favor of JPEG image compression.
However, JPEG compression is lossy, and JPEG quality was hardcoded (75, down from the default of 95).
This can cause noticeable viewer artifacts.
This PR adds: 
- by default, viewer JPEG image format with 90 quality
- configurable viewer PNG compression and JPEG quality settings
=> add quality setting; allow png for lossless compression

nerfstudio/engine/trainer.py
Fix for #1604 
Re-ordering events so websocket port for viewer is checked before potentially lengthy data loading.
=> Check port before loading data

nerfstudio/process_data/realitycapture_utils.py
See #1648 which is caused in part by periods within filename, not only for file extension e.g. `image.problem.jpg`
=> realitycapture: allow periods within filename, not only for file extension

nerfstudio/field_components/encodings.py, tests/field_components/test_encodings.py
Connected to the full KPlanes pull request (https://github.com/nerfstudio-project/nerfstudio/pull/1584) this adds the KPlanesEncoding class which can be used from a KPlanes field. 
It wraps plane creation and interpolation for 3D and 4D input coordinates.
Currently multi-scale planes are not inside the encoding, so they must be added in the field class. lmk what you think about this.
=> Add KPlanesEncoding encoding

nerfstudio/configs/method_configs.py, nerfstudio/viewer/app/src/modules/ViewerWindow/ViewerWindow.jsx
I found that when training nerfacto for a long time (eg. 100000 iter+), it can possibly run into nan, after looking for similar issues, I found https://github.com/nerfstudio-project/nerfstudio/issues/873, and I tried gradient clipping but it did not work, disabling camera optimization helped a little, the training can go to 200000 iter+, but ran nan sooner.
After several experiments, I found that add sigmoid to geo embedding help to prevent from nan, but will reduce the psnr a little. Another better way is to add lr decay through the scheduler, and I do not observe psnr loss. Both ways can lead to 400000 iters training without nan.
Also, I tried logging the variables to determine who appeared nan in the first place, I found it is the mlp_head who output RGB, the vars before it were normal …
=> Update scheduler for nerfacto

nerfstudio/viewer/server/subprocess.py
Hi,
The default websocket port in TIME-WAIT status will cause the port change to a random one. This pull request will fix it.
=> add SO_REUSEADDR option to reuse the port in TIME-WAIT status

nerfstudio/process_data/process_data_utils.py
In this PR, I've added a single print statement to share the number of frames to be extracted from a video during `ns-process-data video ...`.
Previously, the total number of frames in the video was printed but the actual number extracted by ffmpeg was not. This is important information for users because COLMAP runtime has a sharp increase when the number of input images is greater than 1000 (caused by switching linear solver type, [source here](https://github.com/colmap/colmap/issues/116#issuecomment-328452953)) and the `--num-frames-target` argument is approximate, meaning the actual number of frames may be larger than the specified target and cause the user to spend 24+ hours performing COLMAP instead of <4 hours.
Longer term I think the `--num-frames-target` argument should actually …
=> Exposed number of actual frames to extract with ffmpeg for more transparency

nerfstudio/viewer/app/src/modules/ConfigPanel/ConfigPanel.jsx, nerfstudio/viewer/app/src/modules/SidePanel/ExportPanel/ExportPanel.jsx, nerfstudio/viewer/app/src/modules/SidePanel/SidePanel.jsx, nerfstudio/viewer/app/src/reducer.js
The UI would perform multiple slow renders when switching between tabs. This solves some of those rerender issues. 
Old:
https://user-images.githubusercontent.com/3310961/229655941-e4b2a019-d621-4f46-a542-d667a7d831fb.mov
New:
https://user-images.githubusercontent.com/3310961/229655960-57cf548b-630f-440e-b222-f013a3d74f23.mov
=> Optimize viewer UI

nerfstudio/engine/trainer.py
PyTorch allocate GPU memory with async caching. Thus the memory reported by `nvidia-smi` is not the actual memory occupied by tensors. See [PyTorch Memory Management](https://pytorch.org/docs/stable/notes/cuda.html#cuda-memory-management) for more details. The memory for caching is counted by `nvidia-smi` but would not blocking new memory allocation as those memory are considered free memory in PyTorch.
An example: With the following diff patch to reduce the distortion parameter from 6-dim to 4-dim, would lead to 2GB memory increase reported by `nvidia-smi`, but `torch.cuda.max_memory_allocated()` reflects a slightly reduction on memory usage.
```git
diff --git a/nerfstudio/cameras/camera_utils.py b/nerfstudio/cameras/camera_utils.py
index 79490ae6..a068e8c2 100644
--- …
```
=> Monitor actual gpu memory allocation

nerfstudio/cameras/camera_paths.py, nerfstudio/cameras/camera_utils.py, nerfstudio/cameras/rays.py
The `camera_type` will be set in the following lines.
=> Remove useless code in camera_paths

nerfstudio/data/utils/nerfstudio_collate.py
This PR fixes the codebase such that it works with torch 2.0.0.
However IT DOES NOT change the pip dependencies for the following reason:
torch >= 1.13 includes functorch, installing functorch pip package breaks imports (breaks in 2.0.0).
torch < 1.13 does not include functorch and it needs to be installed.
Do we still need to support 1.12?
=> Add support for torch v2.0.0

nerfstudio/utils/writer.py
Current implementation of wandb writer calls wandb.init ignoring WANDB_* environment variables as documented here:
https://docs.wandb.ai/guides/track/environment-variables
This PR changes the implementation such that these env. variables are respected
=> Respect wandb environment variables

docs/developer_guides/viewer/custom_gui.md, nerfstudio/viewer/server/viewer_elements.py, nerfstudio/viewer/viser/__init__.py, nerfstudio/viewer/viser/gui.py, pyproject.toml
The main change is adding a type to the setter/getter for `.value`.
So `checkbox_element.value` will resolve to `bool`, `rgb_element.value` will resolve to `Tuple[int, int, int]`, etc.
=> Improve viewer element types

nerfstudio/viewer/server/viewer_state.py
- In `nerfstudio/viewer/server/viewer_state.py`, adds the condition `self.control_panel.train_util != 1` for rendering while training. This prevents crashing as a result of division by 0 when Train Util is set to `1.00` and completely halts rendering during training, which I believe is reasonable behavior.
=> Fix divide by zero when train util set to 1

nerfstudio/models/base_model.py
This part of data is not used but very big(RaySamples and weights), may cause OOM while evaluate with large images(2000*2000).
=> Delete useless lists of tensors put to CUDA which may cause OOM.

docs/developer_guides/debugging_tools/profiling.md, nerfstudio/configs/base_config.py, nerfstudio/engine/trainer.py, nerfstudio/utils/decorators.py, nerfstudio/utils/profiler.py
This PR adds the support for PyTorch profiler (https://pytorch.org/tutorials/recipes/recipes/profiler_recipe.html)
It also changes the `time_function` decorator to act as a context manager - enabling blocks of code to be timed as well.
Trace example:
=> Add PyTorch profiler to support tracing of forward/backward calls

nerfstudio/engine/trainer.py
I am adding a nerfstudio implementation of the neural scene graph paper, and I tried to use separate nerf(nerfacto) models to represent the background and each foreground object, respectively. However, training such a complex model easily runs into nan issues at early iterations (~3K steps, which is obviously different from the ones in #873). The issue is solved by using grad_scaler only (w/o using amp).
=> add individual grad_scaler config

scripts/viewer/run_viewer.py
The script _run_viewer.py_ crashes when it is provided a config for a pre-trained DreamFusion model.
It is because of _None_ passed to function _viewer_utils.setup_viewer_ via parameter _datapath_,  since generative models (i.e., DreamFusion) are trained without real images.
This commit modifies the code to distinguish _generative_ model from the other.
=> Set data path to launch viewer for DreamFusion

nerfstudio/viewer/app/src/modules/WebSocketUrlField.jsx
When running locally, and not specifying websocket URL, the landing modal showed a hardcoded viewer.nerf.studio link that will take the user away from local viewer.
This PR uses current protocol and host to fix that issue.
=> Use current host in landing page

nerfstudio/viewer/app/package.json, nerfstudio/viewer/app/yarn.lock
Fixes #1773 - so far, Dependabot is clean after this.
But needs broader testing of viewer functionality.
=> force resolutions to newer versions for security

nerfstudio/data/dataparsers/instant_ngp_dataparser.py, nerfstudio/data/utils/dataloaders.py
- Allow using masks with the `instant-ngp-dataloader`
- Move the entire dataset to the GPU when using masks. I feel like this is a reasonable compromise (see [here](https://github.com/nerfstudio-project/nerfstudio/issues/1465))
=> Allow masks with instant ngp dataparser

nerfstudio/data/utils/dataloaders.py
Reverting changes in #1741 as discussed in #1819.
=> Revert loading entire dataset to GPU if using masks

nerfstudio/configs/method_configs.py
Fix the issue #1835:
- change the default `viewer.num_rays_per_chunk` from `1 << 15` to `1 << 12`.
- remove the `render_step_size=0.001` for `instant-ngp-bounded` so that it is automatically calculated based on the scene aabb (target on roughly 1000 samples). Preset `render_step_size` would lead to tons of samples if the scene aabb is large (or in different unit).
=> Reduce the GPU memory required in viewer for NGP methods

docs/quickstart/custom_dataset.md, nerfstudio/process_data/images_to_nerstudio_dataset.py, nerfstudio/process_data/metashape_utils.py, nerfstudio/process_data/process_data_utils.py, nerfstudio/process_data/video_to_nerfstudio_dataset.py
fixes https://github.com/nerfstudio-project/nerfstudio/issues/1634 (see sample runs in that issue)
The COLMAP logic had to be changed slightly, as mentioned here: https://github.com/nerfstudio-project/nerfstudio/issues/1634#issuecomment-1529152231 : after computing the planar projections, the ns-process-data scripts now set the camera type to perspective (which makes sense, since all the rest of the processing is on perspective cameras).
=> Support equirectangular sensor with metashape

nerfstudio/data/pixel_samplers.py
I believe the assert statements on image shape (particularly image dimensions of '3') is unnecessary and redundant in the pixel sampler stage. When writing custom dataparsers, the user has to manage their image format already. In the base InputDataset, there are checks for image dimensions in the get_image() function that handles correct image sizes (3 or 4 channels).
I am working with hyperspectral images and having this assert statement on input dimension size inside the pixel_sampler becomes difficult to work with. I do not want to modify the original sampler logic nor subclass/write my own for my particular multi-dimensional data. The pixel sampler should not have assertions on the image dimension size since this should be done elsewhere. It should focus more on the individual …
=> Remove unecessary assert in pixel sampler on image dimensions

nerfstudio/configs/method_configs.py
- Removes running tests for test_train.py (for a dry-run) when someone implements an external method.
- Adds a short description for the neus-facto method.
=> Avoids running test_train.py on external methods

nerfstudio/data/dataparsers/sdfstudio_dataparser.py
Related to issue: https://github.com/nerfstudio-project/nerfstudio/issues/1732
Related comment: https://github.com/nerfstudio-project/nerfstudio/issues/1732#issuecomment-1543654312
In summary, the [conversion script](https://github.com/autonomousvision/sdfstudio/blob/master/scripts/datasets/process_nerfstudio_to_sdfstudio.py) that is used before training Neus(facto) does not include the `mono_depth_path` and `mono_normal_path` keys for the frames by default. If monocular depth and normal cues are not extracted, some errors will be generated.
There are several ways in which this can be solved.
If another style/approach is preferred, please let me know, so I can change the PR accordingly.
=> #1732 fix sdf dataparser no mono paths

nerfstudio/model_components/losses.py, nerfstudio/models/nerfacto.py, nerfstudio/process_data/colmap_converter_to_nerfstudio_dataset.py
This PR implements gradient scaling from [Radiance Field Gradient Scaling for Unbiased Near-Camera Training](https://gradient-scaling.github.io/)
GradientScaling is added to the nerfacto model and enabled using flag `--use-gradient-scaling=True`
=> Implement gradient scaling

nerfstudio/engine/optimizers.py
fix #1883 #1613.
The reason why there's no inf check is because proposal network did not compute gradient at some iteration step. And there is no need to do optimizer.step for proposal network's parameter.
=> fix pytorch 2.0 optimizer no inf check error

docs/nerfology/methods/index.md, nerfstudio/configs/external_methods.py, nerfstudio/configs/method_configs.py
This PR allows external methods to be discovered and installed from cli (ns-*).
New methods appear under `ns-train --help`. Upon running `ns-train externalmethodname` a message appears and optionally allows the external dependencies to be installed.
=> Discover external methods from CLI

docs/index.md, docs/nerfology/methods/index.md, docs/nerfology/methods/kplanes.md, nerfstudio/configs/external_methods.py
Hi! Finally, the docs for the k-planes add-on. 
Hope the page is clear, but let me know if you have any doubts!
=> Documentation for k-planes add-on

nerfstudio/cameras/rays.py, nerfstudio/engine/callbacks.py, nerfstudio/engine/schedulers.py, nerfstudio/engine/trainer.py, nerfstudio/exporter/marching_cubes.py, nerfstudio/field_components/activations.py, nerfstudio/field_components/encodings.py, nerfstudio/field_components/temporal_grid.py, nerfstudio/fields/base_field.py, nerfstudio/fields/density_fields.py, nerfstudio/fields/nerfacto_field.py, nerfstudio/fields/nerfplayer_nerfacto_field.py, nerfstudio/fields/nerfplayer_ngp_field.py, nerfstudio/fields/sdf_field.py, nerfstudio/generative/stable_diffusion.py, nerfstudio/model_components/losses.py, nerfstudio/model_components/ray_generators.py, nerfstudio/model_components/ray_samplers.py, nerfstudio/models/base_surface_model.py, nerfstudio/models/depth_nerfacto.py, nerfstudio/models/mipnerf.py, nerfstudio/models/nerfplayer_nerfacto.py, nerfstudio/models/tensorf.py, nerfstudio/models/vanilla_nerf.py, nerfstudio/pipelines/base_pipeline.py, nerfstudio/utils/colormaps.py, nerfstudio/utils/misc.py, nerfstudio/utils/plotly_utils.py, nerfstudio/utils/tensor_dataclass.py
This PR fixes some typing issues in models, model_components, fields. Now pyright, vscode (pylance) do not report any errors for these subpackages.
=> Fix some typing problems

nerfstudio/data/pixel_samplers.py
Small fix in `PatchPixelSampler` in case a mask is present.
Tested this while experimenting with InstructNerf2Nerf and a custom dataset that has masks.
=> Fix mask check in PatchPixelSampler

nerfstudio/viewer/server/gui_utils.py
This PR fixes the following bug:
**Describe the bug**
1. `ViewerState` is initialized in the trainer: https://github.com/nerfstudio-project/nerfstudio/blob/160abde6ad0a496aff0b2d7a5fdec90a0f9f6909/nerfstudio/engine/trainer.py#L162
2. This eventually makes a call to `parse_objects` to construct the model tree: https://github.com/nerfstudio-project/nerfstudio/blob/160abde6ad0a496aff0b2d7a5fdec90a0f9f6909/nerfstudio/viewer/server/gui_utils.py#L24
3. If part of the model contains an infinite recursion (e.g. a `torch.nn.Module` that links back to its parent for completely valid implementation reasons), then `parse_objects` will result in a StackOverflow since recursion is repeated indefinitely.
**To Reproduce**
Steps to reproduce the behavior:
1. Create a custom pipeline
2. The custom pipeline …
=> Fix Viewer Recursion: StackOverflow in Server Setup

nerfstudio/cameras/cameras.py
I was getting some annoying warning messages about the functional.resize() function. Apparently pytorch is changing the default value of the 'antialias' parameter from None to True. Adding the parameter as None might be useful.
Link: https://pytorch.org/vision/main/generated/torchvision.transforms.functional.resize.html'
> "The current default is None but will change to True in v0.17 for the PIL and Tensor backends to be consistent."
=> Add antialias parameter as default None

docs/quickstart/installation.md
Https git clone can be run by anyone directly, without account, whereas ssh git on Github requires having a Github account set up.
=> installation.md: Use https instead of ssh for git clone.

nerfstudio/scripts/exporter.py, nerfstudio/viewer/app/src/modules/SidePanel/ExportPanel/ExportPanel.jsx, nerfstudio/viewer/app/src/modules/SidePanel/ExportPanel/MeshSubPanel.jsx, nerfstudio/viewer/app/src/modules/SidePanel/ExportPanel/PointcloudSubPanel.jsx, nerfstudio/viewer/app/src/utils.js
This PR makes the arguments related to normals for point cloud export consistent with the arguments related to normals for Poisson export. Doing this adds support for the use case where a user may want to export just a point cloud with predicted normals instead of o3d estimated normals to use in their own Poisson meshing pipeline.
Additionally, the viewer is updated to reflect the changes.
=> Add option for model normals on ply export

nerfstudio/process_data/process_data_utils.py
Two things in this bug fix: 
1. Remove the output_directory iff it is not the same as the input_directory containing images (we don't want to delete valuable user data accidentally). 
2. Bypass shutil.SameFileError when copying files with a simple try catch. Works fine when input_dir = output_dir.
For some reason my ns-dev-test reformatted some of the longer arguments. I have a recent version of nerfstudio so not sure why it did that.
=> Fix bug when copying images when input_dir = output_dir

nerfstudio/process_data/metashape_utils.py
Reverted back to the original error message when using datasets with multiple camera_model types, also added some extra clarification for the error.
=> Fix metashape multiple camera models error message

nerfstudio/data/datamanagers/base_datamanager.py, nerfstudio/data/dataparsers/nerfstudio_dataparser.py
Also remove the image skipping logic, which seems to be a remnant of some old code (all images should exist).
This allows running inference (s-render or ns-export) without the images.
Fixes https://github.com/nerfstudio-project/nerfstudio/issues/2050
=> nerfstudio dataparser: avoid loading images at inference time

nerfstudio/utils/colormaps.py, nerfstudio/viewer/server/control_panel.py
- Add the trivial "gray" colormap, useful to eg extract accumulation.
- Don't show "pca" in the viewer menu (it crashes the server)
=> colormaps: add "gray"

nerfstudio/process_data/process_data_utils.py
This helps ignore dot files that might mess with processing.
=> Fix data downscale paths

nerfstudio/configs/method_configs.py
=> don't force downscale factor to 1 for nerfacto-huge 

nerfstudio/cameras/camera_optimizers.py
Here I added the possibility for a user to manually tell the Camera Optimizer not to train certain camera indices. This is needed when you know prior that only certain indices should be trained in the camera training_dataset.
=> Add non-trainable camera indices to CameraOptimizer

nerfstudio/data/datamanagers/base_datamanager.py
Closes #2075 and friends, when correct option value is supplied.
`--pipeline.datamanager.masks-on-gpu True`
=> Add option to process masks on GPU for speed at the expense of memory

pyproject.toml
PyColmap version 0.3.0 seems not to be supported in Python >=3.10, preventing nerfstudio[dev] from installing. This PR allows the newer version 0.4.0 to be installed instead.
=> Allow newer pycolmap for newer python

nerfstudio/process_data/process_data_utils.py
Tests have shown that there can be 2 exact same numbers in the output, separated by non-digit symbols. I think it's better to just find the first number.
=> Fix get_num_frames_in_video

nerfstudio/data/datamanagers/base_datamanager.py, nerfstudio/utils/misc.py, tests/data/test_datamanager.py
This PR changes the VanillaDataManager impl. to make the classes truly generic.
It fixes #2102, https://github.com/nerfstudio-project/nerfstudio/pull/1868#issuecomment-1605900681.
Note: it uses features available in Python>=3.8, it would totally break for older pythons.
When implementing #1868, we choose a simpler __class_getitem__ impl. over the original implementation suggested in the first commit of #1868. But the simpler impl. breaks pickling support and causes errors in other places (restored yaml objects are not generic). This PR reverts the original implementation.
=> Fix pickling of VanillaDataManager

nerfstudio/process_data/process_data_utils.py, pyproject.toml
(Note, this may allow other raw image formats to work as well, but I only have some CR2 that I can't share at present.)
=> allow ns-process-data to use CR2 raw images

nerfstudio/fields/tensorf_field.py
Found this bug in tensorf field: if using shperical harmonics (`use_sh=True`), then directions/features encodings are calculated but not used, hence wasting resources.
=> Fix unnecessary encodings calculation in tensorf field

nerfstudio/pipelines/base_pipeline.py, nerfstudio/scripts/eval.py
Adding an optional "render_output_path" parameter to the eval script that saves the rendered image outputs to the specified path.
=> Add option to render evaluated images

docs/quickstart/custom_dataset.md
This pull request is intended to correct an issue found in the project's documentation. The previous version of the documentation used Unix-style "./" notation for file paths, which could potentially confuse or cause issues for Windows users who are expected to use ".\".
- Replaced all instances of "./" path notation with ".\" in the relevant areas of the documentation.
Many developers use Windows systems and the previous documentation would have led to incorrect path usage. With this change, the instructions in the documentation become clearer and more accurate for Windows users, preventing possible confusion and path-related issues.
Please consider merging this pull request to ensure the documentation is correct and clear for all users, irrespective of their operating system. I look …
=> Correct path notation for Windows in documentation

nerfstudio/field_components/encodings.py
When selecting tcnn implementation for HashEncoding, a PyTorch version was still initialized and held in memory, but never used. Now, the PyTorch hash table is only created when selecting PyTorch implementation, or if tcnn is not available.
=> Remove pytorch hash table if tcnn implementation is used

nerfstudio/engine/trainer.py
Avoid zero duration divide-by-zero crash when processing too quickly.
=> Avoid zero duration crash

nerfstudio/process_data/colmap_utils.py
For macOS the `vocab_tree.fbow`  is stored in `Application Support` since the filepath is directly pasted without apostrophes Colmap is searching the file in the `Application` folder rather than going down the full path. Wich results in the following error:
─────────────────────────────────────────────────────────
Error running command: colmap vocab_tree_matcher --database_path austria/colmap/database.db --SiftMatching.use_gpu 1 --VocabTreeMatching.vocab_tree_path /Users/.../Library/Application Support/nerfstudio/vocab_tree.fbow
─────────────────────────────────────────────────────────
F20230711 08:17:11.650357 24696676 visual_index.h:570] Check failed: file.is_open() /Users/.../Library/Application
*** Check failure stack trace: ***
@        0x10510f304  google::LogMessage::Flush()
@ …
=> Fixing Colmap VocabTreeMatching command to support spaces in Filename 

nerfstudio/fields/vanilla_nerf_field.py, nerfstudio/models/vanilla_nerf.py
Parameters default to an instantiated object would remain the same according to [Python doc](https://docs.python.org/3.8/reference/compound_stmts.html#function-definitions)
> Default parameter values are evaluated from left to right when the function definition is executed. This means that the expression is evaluated once, when the function is defined, and that the same “pre-computed” value is used for each call. This is especially important to understand when a default parameter is a mutable object, such as a list or a dictionary: if the function modifies the object (e.g. by appending an item to a list), the default value is in effect modified....
Therefore, the coarse_field and fine_field would share the same RGBFieldHead, which is not the expected behavior.
=> Default fied_heads with instances will cause shared parameters

Dockerfile
With pycolmap, pyceres, and pixsfm we're trying to closely track the dev branch of COLMAP. It's safer to use pined versions when building docker images.
=> Pin versions of pyceres+pixsfm, up pycolmap

nerfstudio/field_components/encodings.py
Introduced handling in `RFFEncoding` for method `get_out_dim(self)` so that if `self.include_input` is True, the result adds the dimension of `in_dim`.
=> Adding input handling for RFFEncoding's get_out_dim(self)

nerfstudio/process_data/colmap_utils.py
Single-quoting filename arguments, as done in #2195, causes colmap to fail on Windows.  
This restores compatibility.
=> Fix colmap vocab_tree_path (#2195) to work with Windows

nerfstudio/pipelines/base_pipeline.py, nerfstudio/scripts/eval.py
=> Add std for eval

nerfstudio/configs/experiment_config.py, nerfstudio/engine/trainer.py
- The loading behavior is similar to that in sdfstudio.
- Allow loading old checkpoints without the schedulers key.
- Versions <= 0.3.2 don't support loading schedulers state_dict, because the states of schedulers are not saved in Trainer.save_checkpoint(). Specifically, commits older than https://github.com/nerfstudio-project/nerfstudio/commit/cebe787bedffd4966fdcb067682da64e168b5565 don't support schedulers loading/saving.
These changes in the commit will save the states of schedulers by default, i.e. creating a schedulers key. Were the checkpoints from previous versions loaded, the loader will check whether the schedulers key exist before loading schedulers.
=> Load schedulers from ckpt in a backward-compatible manner

docs/extensions/blender_addon.md, docs/quickstart/custom_dataset.md, nerfstudio/cameras/camera_paths.py, nerfstudio/cameras/cameras.py, nerfstudio/scripts/render.py
Adding the VR180 camera model to render VR180 video and images. I condensed the omnidirectional stereo and VR180 rendering post processing in the render script. I have updated the documentation for VR180 support as well as the Blender documentation since VR180 rendering is compatible with the Blender add-on.
=> Render VR180 video

nerfstudio/model_components/ray_samplers.py
The existing volumetric sampler code returns 0 as the pixel areas. This PR returns the correct values instead.
=> Use correct pixel area in volumetric sampler

nerfstudio/data/dataparsers/sdfstudio_dataparser.py
Depth supervision for `depth-nerfacto` was added in #1173.
This patch extends that PR to support `sdfstudio` datasets ([as originally intended](https://github.com/nerfstudio-project/nerfstudio/issues/1173#issuecomment-1494633338_)) by adding `depth_unit_scale_factor` to `sdfstudio` metadata.
=> Add depth_unit_scale_factor to sdfstudio_dataparser

nerfstudio/data/datamanagers/base_datamanager.py, nerfstudio/data/datasets/base_dataset.py
Analogous to #2110. This fix speeds up training by over 3x when using multi-gpu DDP.
The observation that prompted this PR: training with `--num-devices=2` is significantly slower than training with single gpu, with extremely high cpu usage (~2600% on a 28-core cpu).
Profiling with `--logging.profiler=pytorch` reveals that `collate_image_dataset_batch()` in `pixel_samplers.py` takes 70ms with `--num-devices=2` and 30ms with single gpu. The batch image tensors are stored on the cpu, so the indexing operation is cpu-intensive.
This PR adds an option to remove `"image"` from `exclude_batch_keys_from_device` to keep the image tensor on the gpu. Using the option with suitable hardware reduces cpu usage from 2600% to 200%, and speeds up 2-gpu training **from ~70 Krays/s to ~250 Krays/s**. …
=> Option to process images on GPU for speed at the expense of memory

README.md, docs/quickstart/installation.md
I just tried an installation on a fresh Ubuntu 22.04 machine, with no system-level CUDA installation.
Unsurprisingly (and as mentioned by @kpertsch), the `tiny-cuda-nn` install step fails without `cuda-toolkit` installed. Running the extra install for `cuda-toolkit` fixes it. I think we should add it to the setup instructions.
A few bits of uncertainty before merging:
- Will a system-level CUDA install break anything here?
- Possibly related: a few people have mentioned needing to fuss with environment variables for all of the linking etc to work. I've never needed to, what's expected here?
- @kpertsch also reported needing to update `gcc` via `conda install -c conda-forge gcc=11.2 gxx=11.2`. We may want to add this to the FAQ.
- Perhaps we should add a note about supported NVIDIA driver …
=> More robust install instructions

docs/quickstart/installation.md
Shouldn't be necessary when `cuda-toolkit` is installed via `conda`.
=> Remove system-level CUDA install from install instructions

nerfstudio/process_data/colmap_converter_to_nerfstudio_dataset.py, nerfstudio/process_data/images_to_nerfstudio_dataset.py, nerfstudio/process_data/process_data_utils.py
Use `ns-process-data images --no-same-dimensions` ... to handle image sets with different dimensions properly, by disabling same-dimensions optimizations.  (Fast downscaling assumes image dimensions are the same.)
Fixes #2293 when --no-same-dimensions is specified, which behaves correctly but unfortunately runs slower.
=> Allow same dimensions optimizations to be disabled

nerfstudio/process_data/process_data_utils.py
The fast-downscale path apparently relies on being able to overwrite the original file (eg. with crop etc. applied) which fails for TIFF, but works for JPG.  This restores support for raw images as input; fixes #2296.
=> convert raw to JPG not TIFF, to avoid fast-downscale ffmpeg error

nerfstudio/data/datasets/depth_dataset.py, nerfstudio/utils/misc.py
(for systems needing https://github.com/nerfstudio-project/nerfstudio/pull/1982
e.g. Windows)
=> When generating depth images, use torch_compile with ZoeDepth for compatibility

Dockerfile, docs/quickstart/installation.md
A fix for #1130. It's not possible to write into a volume with a wrong user making it more hassle to train.
=> fix: Allow custom user ID

nerfstudio/data/dataparsers/instant_ngp_dataparser.py
To support issue #2318 problems, I choose to add split codes similar to nerfstudio data parser for instant ngp dataparser.
After I add the code, I run `ns-train nerfacto --data ${mypath} --output ${mypath} instant-ngp-data` and open it in the viewer, I can see this, 
which shows the split has been made.
=> fix #2318: add train/test/eval split for instant ngp dataparser

nerfstudio/process_data/images_to_nerfstudio_dataset.py
Percent_radius_crop was inside video processing, but not images. This fixes that
=> Circle crop to images processing pipeline

nerfstudio/viewer_beta/control_panel.py, nerfstudio/viewer_beta/viewer_elements.py, pyproject.toml
The latest release of `viser` renames `GuiHandle` to `GuiInputHandle`, since there are now non-input GUI handles. I added a shim so it shouldn't produce any runtime errors (and/or actually break any `nerfstudio` installations), but it's hidden to the type checker and will produce a `pyright` error.
=> viser 0.1.0, fix type checker errors

nerfstudio/engine/optimizers.py
I believe there is a bug in the Optimizers.scheduler_step() method:
Calling Optimizers.scheduler_step() results in the error:
> 'dict' object has no attribute 'param_group_name'
Here is a minimal script to produce the error:
```
import torch
from nerfstudio.engine.optimizers import Optimizers, AdamOptimizerConfig
from nerfstudio.engine.schedulers import ExponentialDecaySchedulerConfig
optimizers_config = {
"fields": {
"optimizer": AdamOptimizerConfig(lr=1e-2, eps=1e-15),
"scheduler": ExponentialDecaySchedulerConfig(lr_final=0.0001, max_steps=200000),
}
}
dummy_params = [torch.tensor([42.0])]
param_groups = {"fields": dummy_params}
optimizer = Optimizers(optimizers_config, param_groups)
optimizer.optimizer_step("fields")
optimizer.scheduler_step("fields")
```
=> Optimizers.scheduler_step() bug fix

nerfstudio/scripts/downloads/download_data.py
Changing the location of where the Nerfstudio Dataset is hosted. The prior URLs will be deleted from their location upon merge into main.
=> Switching Nerfstudio Dataset data to GDrive URLs

nerfstudio/process_data/equirect_utils.py, pyproject.toml
The equilib package was under a GPL so we couldn't use it in nerfstudio since nerfstudio is MIT. I just implemented the equirectangular to perspective method from [this MIT licensed library](https://github.com/kaustubh-sadekar/OmniCV-Lib) in pytorch and then used it instead.
=> Added a pytorch implementation of OmniCV's to remove equilib package usage

docs/quickstart/installation.md
To prevent abusing of root privilege, please use custom user privilege to start.
If not, sometimes the Docker images may be started with the permissions of root or other users. If you modify the mounted files in the container , it will cause permission errors or other errors.
=> Fix the starting command of docker.

nerfstudio/data/datasets/depth_dataset.py, nerfstudio/data/pixel_samplers.py, nerfstudio/model_components/losses.py, nerfstudio/models/depth_nerfacto.py
PR #2066 adds a very nice ranking-based loss that can be used with non-metric depth. The ranking loss can also be used with metric depth, and seems to provide smoother results on the replica dataset (image below). 
This PR is a minimal set of changes that allows the ranking loss to be used with depth read from disk (usually GT/sensor depth).
=> Enable SparseNerf depth ranking loss to be used with GT/Sensor depth

nerfstudio/model_components/renderers.py
running `ns-train vanilla-nerf` resulted in the following error:
```bash
Traceback (most recent call last):
File "/usr/local/bin/ns-train", line 8, in <module>
sys.exit(entrypoint())                                 
File "/project_ghent/projects/nerfstudio/nerfstudio/scripts/train.py", line 261, in entrypoint
main(                                                  
File "/project_ghent/projects/nerfstudio/nerfstudio/scripts/train.py", line 246, in main
launch(                                                
File "/project_ghent/projects/nerfstudio/nerfstudio/scripts/train.py", line 189, in launch
main_func(local_rank=0, world_size=world_size, config=config)
File "/project_ghent/projects/nerfstudio/nerfstudio/scripts/train.py", line 100, in train_loop
trainer.train() …
```
=> cast background to device

Dockerfile
ARG commands before FROM are not visible inside the build unit (after the FROM) unless specified again [without default values](https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact).
Dockerfile will not build without this fix.
=> Fixes ARG before FROM bug

tests/test_train.py
Use `tmp_path` [pytest fixture](https://docs.pytest.org/en/7.1.x/how-to/tmp_path.html#the-tmp-path-fixture) during `test_train` to direct the config `output_dir` to temporary pytest subdirectory. Also call to `config.set_timestamp()` to set timestamp on config training directory.
=> test_train tmp_path

docs/developer_guides/new_methods.md, docs/reference/api/optimizers.rst
Build API docs for `nerfstudio.engine.trainer` and `nerfstudio.engine.callbacks`.  
Additional minor correction in `docs/developer_guides/new_methods.md`.
=> engine docs

nerfstudio/viewer/app/src/modules/Scene/Scene.jsx
Hi, 
In the web viewer, rotate up/down via mouse drage not work when pressing `w`:
https://github.com/nerfstudio-project/nerfstudio/assets/564361/981b5daa-52b8-4c1d-b007-3941dc49d027
and the camera will be freezed after pressing `w` for a while:
https://github.com/nerfstudio-project/nerfstudio/assets/564361/199eadfa-50b4-48cd-8bd9-a6f7ece54b9f
Current implementation will led to `position` === `target`: https://stackoverflow.com/questions/47503286/why-do-three-js-trackball-controls-freeze-if-camera-position-controls-target
This modification can fix these problems:
https://github.com/nerfstudio-project/nerfstudio/assets/564361/bb04bc71-909d-4555-9221-7f65889f74c3
https://github.com/nerfstudio-project/nerfstudio/assets/564361/b842d754-2714-442d-908c-47ab91ce993a
=> Fix the problem that camera will be freezed when moving forward

nerfstudio/process_data/process_data_utils.py
We should always be using `-vsync vfr`, even when extracting all frames.
Not doing so results in many times more frames extracted than we expect (i.e. 37891 vs 4143 in my case), and they're not even "real" useful frames.
Not something you would normally run into if you're doing things right, but in doing some A/B testing of different methods of preprocessing, I ran into it anyway.
=> Fix issue when extracting all frames from a video.

nerfstudio/data/dataparsers/colmap_dataparser.py
This PR adds an option to the colmap parser, which allows it to load 3D points. These points can be used in methods like tetra-nerf or Gaussian splatting.
=> Allow colmap parser to load 3D points

nerfstudio/data/dataparsers/colmap_dataparser.py
This PR makes the following changes to the colmap dataparser:
- Optional paths are relative to config.data
- Fixes downscaling for depth/mask data
- Downscale respects deep image paths (previously it would fail with more then 1 level)
=> Colmap parser: fix downscale for complex paths

Dockerfile, nerfstudio/field_components/encodings.py, nerfstudio/field_components/mlp.py, nerfstudio/fields/sdf_field.py, nerfstudio/utils/external.py, tests/field_components/test_fields.py
Also, this enables the ns-install-cli to work inside docker build context without requiring cuda-docker-runtime
=> Fix import error when tcnn installed but CUDA runtime not available

nerfstudio/scripts/train.py
When running `ns-train --load-config $CONFIG_PATH` currently the timestamp is fixed to what was in the config file, which is probably fine. But when I omit the `timestamp` parameter from the config file, it would be nice to have a new timestamp be set. Instead, the current implementation leaves the timestamp value as the default string value "{timestamp}" instead of a new valid timestamp. 
I believe we can fix this with a single line change, by moving the call to `config.set_timestamp()` to after loading the config file. I don't see how this will impact anything else.
This won't affect people who want their timestamp fixed to what the config file reads because `config.set_timestamp()` only sets the value if it is set to the default value "{timestamp}" due to the if statement here: …
=> Allow the option for timestamp to be generated for `ns-train --load-config`

nerfstudio/configs/base_config.py, nerfstudio/configs/experiment_config.py, nerfstudio/engine/trainer.py, nerfstudio/scripts/viewer/run_viewer.py, nerfstudio/viewer_beta/viewer.py, pyproject.toml
This PR adds initial support for shareable links to the beta viewer.
Link generation can be enabled via `--share True` on either `ns-train` or `ns-viewer`. For example,
```
ns-train nerfacto --data ./data/nerfstudio/person --vis viewer_beta --share True
```
wil print:
Which, thanks @jonahbedouch's efforts on mobile support, we can open on a phone!
An example URL is https://edge-based-relational-7462.share.viser.studio, which I'll keep up for a few hours if anybody wants to check that they can access it.
Once the final beta viewer features are stable, this can also help with Colab tunnel issues + various port forward-related roadblocks that folks seem to be having (#1908 #2433 #2439).
=> Add share link support for beta viewer

nerfstudio/fields/vanilla_nerf_field.py
In case it is used in a proposal network we avoid initializing the head.
=> Do not materialize mlp_head if no field_heads

.vscode/settings.json
in #2086 @kerrj  changed the vscode settings to ms-python.black-formatter but should have also changed the way the arguments are passed to it.
=> .vscode settings match move to ms-python.black-formatter

nerfstudio/model_components/ray_samplers.py
This allows custom `PDFSamplers` (e.g. mipnerf360 samples intervals instead of points) in distinct repositories or future versions while still using the base `ProposalNetworkSampler`.
=> Allow custom sampler in ProposalNetworkSampler

nerfstudio/viewer_beta/viewer.py
With the current "Custom Elements" folder generation, you end up with duplicate folder structures like below:
Given this ViewerText in nerfacto.py
The folder appears as
This is because viser's `gui_add_folder` creates a unique ID for every folder -- there can exist two folders with the exact same names, but with different IDs --> duplicate structures. 
https://github.com/nerfstudio-project/nerfstudio/blob/53037ba8a790a7aa089c8a4983c2aa210e01111c/nerfstudio/viewer_beta/viewer.py#L171
This PR changes the viewer element population code to keep track of all the generated folders (with their respective paths), so that the previously folder contexts are used instead of re-generating them (if applicable).
With the PR the structure should be fixed:
, with it also working for nested structures as …
=> Track all viser GUI folders to avoid folder duplicates (viewer-beta)

docs/quickstart/custom_dataset.md
Deprecate `apt` with `conda` for colmap installation to ensure correct version 3.8 with CUDA support.
=> Update colmap installation instructions with conda

nerfstudio/configs/experiment_config.py
In our previous PR https://github.com/nerfstudio-project/nerfstudio/pull/2431, we forgot to update the is_viewer_enabled function, causing an issue where Comet and the Viewer could not be used simultaneously. This issue has now been resolved. Additionally, I took the opportunity to slightly refactor the function, making it easier to update in the future.
=> Add support of using both Comet and Viewer at the same time

docs/developer_guides/pipelines/datamanagers.md, nerfstudio/data/datamanagers/base_datamanager.py, nerfstudio/scripts/render.py, nerfstudio/utils/eval_utils.py, tests/data/configs/test_config1.yml, tests/data/configs/test_config2.yml
`eval-image-indices` is never used. Remove from configs.
Adresses #1963
=> Remove unused config param

nerfstudio/field_components/encodings.py
The previous implementation caused a training crash. Fix it according to VMEncoding.
=> (minor) Align upsampling in TensorCPEncoding with TensorVMEncoding

docs/quickstart/data_conventions.md
Updated the documentation to explicate that zero value in depth images is treated as unknown depth. This behavior is defined in https://github.com/nerfstudio-project/nerfstudio/blob/a484d255b4f71c55915afcfc52d90ec88963779f/nerfstudio/model_components/losses.py#L242
=> Add documentation about unknown depth pixel convention

README.md, docs/quickstart/custom_dataset.md, nerfstudio/process_data/odm_utils.py, nerfstudio/scripts/process_data.py
Hello :wave: ,
this PR adds support for converting ODM (https://github.com/OpenDroneMap/ODM) datasets to nerfstudio format.
Usage:
1. Process a dataset using [ODM](https://github.com/OpenDroneMap/ODM#quickstart)
```bash
$ ls /path/to/dataset
images
odm_report
odm_orthophoto
...
```
2. Convert to nerfstudio format.
```bash
ns-process-data odm --data /path/to/dataset --output-dir {output directory}
```
3. Train as usual.
Results:
Dataset: https://hub.dronedb.app/r/odm/brighton-beach
https://github.com/OpenDroneMap/ODM/assets/1951843/c834bb72-a02e-456a-80c0-e9887644d3cc
Dataset: https://github.com/pierotofy/dataset_banana
Hope this can be useful to others. Let me know if changes are needed. :pray:
=> Add ODM data processor

README.md, docs/nerfology/methods/instant_ngp.md, docs/quickstart/custom_dataset.md, docs/reference/contributing.md, nerfstudio/configs/external_methods.py, nerfstudio/viewer/app/src/modules/Banner/Banner.jsx, nerfstudio/viewer/app/src/modules/LandingModal/LandingModal.jsx, nerfstudio/viewer/app/src/modules/ViewportControlsModal/ViewportControlsModal.jsx
Update the image URLs and documentation links due to change in docs url structure. Files edited include readme, documentation, and legacy viewer files.
=> Update URLs for readme and image references

nerfstudio/viewer_beta/render_panel.py, nerfstudio/viewer_beta/viewer.py
Added a gui dropdown menu for selecting the camera type in the viser viewer render panel. Currently, the render view doesn't update to preview the equirectangular or fisheye render but the user select the camera type which updates the camera_path json file.
Also updated image url of the nerfstudio logo in the viewer
=> Add camera_type dropdown in new viewer

nerfstudio/data/datamanagers/base_datamanager.py, nerfstudio/data/datamanagers/parallel_datamanager.py
This correct the "Train Rays / Sec" when using DynamicBatchPipeline
=> Fix datamanagers' get_rays_per_batch functions in case of using DynamicBatchPipeline

nerfstudio/configs/dataparser_configs.py, nerfstudio/data/dataparsers/scannetpp_dataparser.py
Dataparser for the [ScanNet++](https://kaldir.vc.in.tum.de/scannetpp/) dataset adapted from the nerfstudio dataset. The dataset parser follows the dataset file structure and can be used by specifying the dataset root and the scene ID.
Example usage
```shell
DATA_ROOT=SCANNETPP_DATASET_ROOT
SCENE_ID=036bce3393
ns-train nerfacto \
--max_num_iterations 100000 \
--pipeline.datamanager.train_num_rays_per_batch 8192 \
--pipeline.datamanager.train_num_images_to_sample_from 400 \
--pipeline.datamanager.train_num_times_to_repeat_images 100 \
--vis viewer+tensorboard \
scannetpp-data \
--data ${DATA_ROOT} \
--scene-id ${SCENE_ID} \
--scene_scale 1.5
```
The scene contain more than 1k images. Set `train_num_images_to_sample_from` and `train_num_times_to_repeat_images` to avoid cpu out-of-memory. …
=> Add scannetpp dataparser

nerfstudio/data/datamanagers/base_datamanager.py
It's a small point, but I can't bear it after I see it many times. Every time I see it, I feel bad there misses a space, sorry so I changed it!
https://github.com/nerfstudio-project/nerfstudio/blob/e2060793705f8a6f2b0533dd844991050c6c1760/nerfstudio/data/datamanagers/base_datamanager.py#L345
=> Missing a space in base_datamanager.py

Dockerfile
**Building the Dockerfile** of the current `main` branch **fails** with the error message
```
failed to solve: process "/bin/bash -c git clone --recursive https://github.com/cvg/pixel-perfect-sfm.git &&     git reset --hard 40f7c1339328b2a0c7cf71f76623fb848e0c0357 &&     git clean -df &&     cd pixel-perfect-sfm &&     python3.10 -m pip install -e . &&     cd .." did not complete successfully: exit code: 128
```
due to the [wrong order of the commands](https://github.com/ahmed-shariff/nerfstudio/blob/57c0693f94b0aa3f3e7aadd62c1b78888c747136/Dockerfile#L152-L154) introduced in https://github.com/nerfstudio-project/nerfstudio/pull/2446. This pull request fixes this by inverting their order.
=> Fix pixel-perfect-sfm installation in Dockerfile

nerfstudio/process_data/colmap_converter_to_nerfstudio_dataset.py, nerfstudio/process_data/colmap_utils.py
ns-process-data will still refine intrinsics by default for compatibility.
Specify --no-refine-intrinsics to turn off.
=> make refine intrinsics during ns-process-data optional

nerfstudio/viewer_beta/render_panel.py, nerfstudio/viewer_beta/render_state_machine.py
Small changes for the new viewer including changing the FPS slider to a text entry and fixing the incorrect resolution text box description.
Added a check if render_time is non zero in the render_state_machine.py in the new viewer due to a divide by zero error occasionally causing the viewer to stop running. I noticed this usually happened when using nerfacto-huge.
=> Few viewer changes

nerfstudio/process_data/colmap_converter_to_nerfstudio_dataset.py, nerfstudio/process_data/colmap_utils.py
This PR includes #2550 (already merged to main) which allows one to specify `--no-refine-intrinsics`, 
and also more importantly, adds a missing equals sign from multinerf.
That seems to fix the discrepancy I was seeing with ns-process-data images.
(Actually may want to merge that to main as well)
=> Gaussian splatting process data fixes

nerfstudio/process_data/colmap_utils.py
(Bringing over the rest of #2554 to main.)
=> ns-process-data images fix: multinerf uses equals sign

nerfstudio/models/instant_ngp.py, nerfstudio/models/mipnerf.py, nerfstudio/models/tensorf.py, nerfstudio/models/vanilla_nerf.py
Here is a proposal to add gradient scaling as an option to other methods like instant-ngp, mipnerf, tensorf, vanilla-nerf.  It is disabled by default so it won't change existing behaviour. The code was copied from the nerfacto method.
=> Add gradient scaling option to more methods

nerfstudio/configs/base_config.py, nerfstudio/viewer_beta/control_panel.py, nerfstudio/viewer_beta/viewer.py
I added two parameters to the Viewer config. Now we can change the size of the training & eval camera frustums, and we can enable/disable rendering the scene with depth compositing. This is useful for (1) when the scene is small and frustums are too tiny or (2) when there are floaters or artifacts in the way and you still want to see the camera frustums.
**Default, trained for a little bit.**
```bash
ns-train nerfacto --data data/nerfstudio/plane --vis viewer_beta
```
**Modifying the camera frustum scale from the default 0.1 to 1.0 (10x) and turning off depth compositing.**
```bash
ns-train nerfacto --data data/nerfstudio/plane --vis viewer_beta --viewer.camera_frustum_scale 1.0 --viewer.default_composite_depth False
```
=> Expose camera frustums size and occlusions to CLI

nerfstudio/viewer_beta/control_panel.py, nerfstudio/viewer_beta/viewer.py
Prints the share URL or localhost port in the green banner at the bottom for the viewer beta, previously it was broken
=> Print beta URL in banner correctly

nerfstudio/cameras/camera_utils.py
Eager backend support in torch.compile seems not to support the reduce-overhead mode anymore. This PR switches to the default inductor backend. Some data points: https://github.com/nerfstudio-project/nerfstudio/pull/1922
@kerrj 
Adresses #2438.
=> Fix torch.compile for torch 2.1

nerfstudio/cameras/camera_utils.py
Re commit 85677d310fcb8700b284225de646c63bb02b83de, which caused the following when training nerfacto:
=> Remove compile line in camera_utils

nerfstudio/viewer_beta/viewer.py
Re #2542. Fix index bug by creating two different iterators in `update_camera_poses`, since `self.original_c2w`(dict) and `c2ws_delta`(np array) should be indexed into differently.
=> Fix large dataset (> 512 images) training in viewer_beta

tests/utils/test_math.py
This test is failing sporadically. It seems to be a floating point precision issue. (the issue goes away for me when I switch everything to float64)
=> Make spherical harmonics test more forgiving

nerfstudio/viewer_beta/viewer.py
ViewerElements are scraped on pipeline, but ViewerControl is currently being scraped on trainer. This is problematic for `ns-viewer`, because trainer is not instantiated then.
https://github.com/nerfstudio-project/nerfstudio/blob/9528a3f717fe28a6c6500199b5b37d4f2c6e10ca/nerfstudio/viewer_beta/viewer.py#L209
https://github.com/nerfstudio-project/nerfstudio/blob/9528a3f717fe28a6c6500199b5b37d4f2c6e10ca/nerfstudio/viewer_beta/viewer.py#L216
=> Bugfix; scrape pipeline for viewercontrol, not trainer

nerfstudio/cameras/cameras.py
Tangential camera distortion parameters have flipped y in the current implementation. This is because OpenCV camera model assumes opencv coords, but the coords are passed as opengl. This PR moves the switch from opencv to opengl after the distortion.
=> Fix tangential camera distortion (p1,p2 in opencv camera)

docs/developer_guides/viewer/viewer_control.md, nerfstudio/viewer_beta/viewer_elements.py
In the original viewer, a user could click on a point in the screen, to specify a "ray"-like interaction (akin to a pointer finger stick originating from the client camera, going through the clicked pixel on the image plane).
This replicates the original capability in viewer_beta, with a few differences:
- Functionality to remove scene click listeners, once instantiated (`unregister_click_cb`)
- Wraps the scene click events (which take as input nerfstudio's `ViewerClicks`) inside a function that takes as input `ScenePointerEvent`, for viser-nerfstudio compatibility.
(Implementation based on the recently integrated viser PR https://github.com/nerfstudio-project/viser/pull/106)
=> Integrate scene click capability from original viewer

nerfstudio/viewer_beta/render_panel.py, pyproject.toml
I cleaned up the spline rendering a little bit[^1] and added spherical [^2] handles for transitions, which you can click on to adjust timing between keyframes.
Here's an example workflow, where we make the transition between a pair of keyframes faster:
https://github.com/nerfstudio-project/nerfstudio/assets/6992947/c7d06cc5-ae2b-4b20-9c2e-6ae5d7d67372
As an aside: the render panel code is adapted from research code and really chaotic. I spent a little bit of time trying to refactor and couldn't come up with something I was super happy with; I'd like to revisit this from viser in a "recommended usage patterns" kind of way.
[^1]: via https://github.com/nerfstudio-project/viser/pull/77, thanks @origamiman72!
[^2]: via https://github.com/nerfstudio-project/viser/pull/132, thanks @pritzza!
=> Keyframe timing for beta viewer

nerfstudio/data/dataparsers/nuscenes_dataparser.py
The ParallelDataManager (see #2092) makes pytorch crash if the cameras instance's fx, fy, cx or cy tensors are loaded from a common shared tensor.
This PR fixes the issue by cloning the respective tensors before passing them to the `Cameras(...)` constructor.
=> Make nuScenes dataparser compatible with ParallelDataManager

nerfstudio/configs/base_config.py, nerfstudio/configs/experiment_config.py, nerfstudio/data/datamanagers/base_datamanager.py, nerfstudio/data/dataparsers/base_dataparser.py, nerfstudio/models/base_surface_model.py, nerfstudio/models/nerfacto.py, nerfstudio/models/tensorf.py, nerfstudio/pipelines/base_pipeline.py
Converted many @dataclass assignments to field()s for python 3.11 compatibility
There are probably more to go, as I only tested this with ns-train nerfacto.
=> Converted many @dataclass assignments for python 3.11 compatibility

nerfstudio/process_data/colmap_utils.py
When you build colmap from source you get the '3.9-dev' version and the old code would try to turn it to a float to figure out the version number and crash. I changed it to only parse digits and decimals.
=> Ns-process-data bug with dev version of colmap

README.md, docs/quickstart/custom_dataset.md, nerfstudio/cameras/camera_utils.py, nerfstudio/cameras/cameras.py, nerfstudio/data/datamanagers/base_datamanager.py, nerfstudio/data/dataparsers/nerfstudio_dataparser.py, nerfstudio/data/pixel_samplers.py, nerfstudio/scripts/datasets/process_project_aria.py, nerfstudio/scripts/process_data.py, pyproject.toml
1) An export script for processing Project Aria datasets
2) Add support for Fisheye624 cameras
3) Add support for center-crop masking and sampling
Example commands for running nerfstudio on Project Aria data:
```
python scripts/datasets/process_project_aria.py --vrs_file=<path_to_vrs> --mps_data_dir=<path to MPS directory> --output_dir=<nerfstudio_data_dir>
ns-train nerfacto --data <nerfstudio_data_dir>  nerfstudio-data --orientation-method none
=> Add support for Project Aria datasets.

nerfstudio/data/datamanagers/full_images_datamanager.py, nerfstudio/models/gaussian_splatting.py
When I try to use the mask images in 3dgs branch of nerfstudio, I encounter the error 
> cv2.error: OpenCV(4.6.0) error: (-5:Bad argument) in function 'undistort'
> Overload resolution failed:
>  - src data type = 0 is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'
I guess this is because we save the masks as bool somewhere in data_util and here we need to convert it back to uint8 before undistorting it.
=> Fix the bugs of mask input in gaussian-splatting branch

nerfstudio/models/gaussian_splatting.py
I found a bug of random quaternions generation in gaussian-splatting model. This is used when initializing the gaussians.
=> Fix a bug of random quaternions

nerfstudio/scripts/datasets/process_project_aria.py, nerfstudio/viewer_beta/control_panel.py, nerfstudio/viewer_beta/render_panel.py, nerfstudio/viewer_beta/render_state_machine.py, nerfstudio/viewer_beta/utils.py, nerfstudio/viewer_beta/viewer.py, nerfstudio/viewer_beta/viewer_elements.py, pyproject.toml
**(1) Continuos velocity trajectories**
Previously, velocities in the beta viewer were piecewise linear. I think this was because I misinterpreted some of the original viewer code.
This new implementation produces nicer splines with continuous velocities:
**(2) Better render preview**
We now support previewing fisheye + equirectangular renders, hide threejs elements during previews, and respect the render aspect ratio.
https://github.com/nerfstudio-project/nerfstudio/assets/6992947/178ff7ab-8f7f-48f4-b980-a6afc48fd3eb
=> Improved render panel for beta viewer

nerfstudio/data/datamanagers/parallel_datamanager.py, pyproject.toml
Fix the issue of training periodically stuck at https://github.com/nerfstudio-project/nerfstudio/blob/a8e6f8fa3fd6c0ad2f3e681dcf1519e74ad2230f/nerfstudio/data/datamanagers/parallel_datamanager.py#L280
```
ns-train nerfacto --data data/nerfstudio/poster --max-num-iterations 200
```
**Reason**: `wait()` will be triggered in `.result()` due to the incomplete async put: `self.out_queue.put_nowait((ray_bundle, batch))`.
**Fix**: Change the put from async to sync. Don't need `ThreadPoolExecutor` anymore to acquire data from the queue.
=> Fix periodically stuck in parallel datamanager

nerfstudio/viewer_beta/viewer_elements.py
Allow `ViewerElement` visibility to be set upon initialization. 
Currently, *all* elements are always set to visible. 
However, it might be good to intentionally make elements invisible from the get-go, like the dropdown example below. This is not possible in the current code, because `ViewerElement`'s `gui_handle` is initialized *after* the pipeline. 
Corresponding code is also attached. 
```
self.viewer_0_selection = ViewerDropdown(name="Options", default_value="1", options=["1", "2"])
self.viewer_1_button_1 = ViewerButton(name="Button 1", visible=True,  cb_hook=lambda _: None)
self.viewer_1_button_2 = ViewerButton(name="Button 2", visible=False, cb_hook=lambda _: None)
def swap_visible_button(dropdown: ViewerDropdown):
if dropdown.value == "1":
self.viewer_1_button_1.set_visible(True) …
```
=> Add `visible` as kwarg to ViewerElements

nerfstudio/data/datamanagers/full_images_datamanager.py
- skipping cache image for `no-cache` argument
=> fixed not cache images for full image datamanager

nerfstudio/scripts/downloads/download_data.py
This adds the [Mill 19](https://meganerf.cmusatyalab.org/#data) dataset to the ns-download-data script and converts it to the format that the nerfstudio data parser expects:
=> Add Mill 19 dataset

nerfstudio/configs/experiment_config.py, nerfstudio/data/datamanagers/base_datamanager.py, nerfstudio/data/datamanagers/full_images_datamanager.py, nerfstudio/models/base_surface_model.py, nerfstudio/models/gaussian_splatting.py, nerfstudio/pipelines/base_pipeline.py, tests/plugins/test_registry.py
Following the [Training your first model](https://docs.nerf.studio/quickstart/first_nerf.html#training-your-first-model) docs using Python 3.11:
```console
$ ns-train nerfacto --data data/nerfstudio/poster
Traceback (most recent call last):
File "/home/matthew/.conda/envs/nerfstudio311/bin/ns-train", line 5, in <module>
from nerfstudio.scripts.train import entrypoint
File "/home/matthew/Repositories/nerfstudio/nerfstudio/scripts/train.py", line 62, in <module>
from nerfstudio.configs.method_configs import AnnotatedBaseConfigUnion
File "/home/matthew/Repositories/nerfstudio/nerfstudio/configs/method_configs.py", line 28, in <module>
from nerfstudio.configs.external_methods import get_external_methods
File "/home/matthew/Repositories/nerfstudio/nerfstudio/configs/external_methods.py", line …
```
=> Fix Python 3.11 dataclass field default_factory defaults

README.md, docs/quickstart/installation.md
I couldn't get `gsplat` to build automatically from a PyPI install on any of my servers with torch 2.0.1. `gsplat` worked fine when installing from the git repo.
The root cause was that my CUDA libraries, when installed via conda, needed to be linked from `$CUDA_HOME/lib` and not `$CUDA_HOME/lib64`. This is fixed in 2.1: https://github.com/pytorch/pytorch/pull/101285
=> Update docs to recommend torch 2.1

Dockerfile
This commit adds the `--no-cache-dir` option to the `pip install` command in the [`Dockerfile`](https://github.com/nerfstudio-project/nerfstudio/blob/main/Dockerfile).  By including this option, the cache during Python package installation is disabled, resulting in a significant reduction (approximately 3.2GB) in disk usage during `docker build`.
Without this option, the Docker image would contain the following cache, which is unnecessary:
```shell
du -sh /home/user/.cache/pip
```
=> Add --no-cache-dir option to pip install in Dockerfile

nerfstudio/engine/trainer.py, nerfstudio/scripts/viewer/run_viewer.py, nerfstudio/utils/writer.py, nerfstudio/viewer/viewer.py
We now print `localhost:port` instead of `0.0.0.0:port` when the viewer is bound to `0.0.0.0`. The latter was confusing people.
I also removed the ANSI code that makes the viewer URL blink, but can re-add it if anybody prefers to have that feature retained!
closes #2740
=> Improve viewer banner when server is bound to 0.0.0.0

pyproject.toml, setup.cfg
~~Move `dependency_links` to `setup.cfg`~~
`[options]` is not a valid table in `pyproject.toml`: https://packaging.python.org/en/latest/specifications/pyproject-toml/
but it is in `setup.cfg`: https://setuptools.pypa.io/en/latest/deprecated/dependency_links.html
=> Remove deprecated dependency_links config

nerfstudio/configs/base_config.py, nerfstudio/scripts/viewer/run_viewer.py
Looks like this argument is both redundant (there's both `--make-share-url` and `--viewer.make-share-url`) and ignored (immediately overwritten)!
=> Remove unused make_share_url arg in ns-viewer

pyproject.toml
Installing nerfstudio on NVIDIA Jetson throws an error:
```
ERROR: Could not find a version that satisfies the requirement pymeshlab>=2022.2.post2; 
platform_machine != "arm64" (from nerfstudio) (from versions: none)
```
This PR fixes the issue, enabling installation of nerfstudio on AArch64 machines.
=> Update dependencies for aarch64

nerfstudio/data/datamanagers/full_images_datamanager.py, nerfstudio/data/datasets/base_dataset.py, nerfstudio/models/gaussian_splatting.py, nerfstudio/scripts/render.py
See also https://github.com/nerfstudio-project/nerfstudio/issues/2735
This PR also changes the default behavior of GS training to cache images in bytes. Other models in nerfstudio are not impacted (still caching in float32). There is no sensible slow-down in the training.
=> Add option of caching image in bytes rather than float32

nerfstudio/data/dataparsers/colmap_dataparser.py, nerfstudio/data/dataparsers/nerfstudio_dataparser.py
Simple change, this is to ensure 1600 pixels is the maximal (inclusive) dimension in auto-downscaling. This behavior is consistent with several other repos such as Inria Gaussian Splatting ( https://github.com/graphdeco-inria/gaussian-splatting/blob/main/utils/camera_utils.py#L26 )
=> MAX_AUTO_RESOLUTION is ensured in auto downscale

pyproject.toml
The `projectaria-tools` package doesn't have Windows binaries, which prevents `pip install -e .[dev]` from working. I've updated the specification to require a platform other than Windows for installation. I also updated the specification to not use `[all]` after a discussion with the library authors, and fixed an underscore typo which was probably being silently transformed by `pip`.
Previously (https://github.com/nerfstudio-project/nerfstudio/pull/2672), I had also disabled `pycolmap`, but it turns out that very recently (as of Jan 11), there's now Windows wheels published for `pycolmap` on PyPi (https://pypi.org/project/pycolmap/#files), so it actually installs just fine. I also posted about that in the associated issue (https://github.com/nerfstudio-project/nerfstudio/issues/1480) in …
=> Disable projectaria tools on Windows

docs/nerfology/methods/splat.md
We have `--cull_alpha_thresh` and `--cull_scale_thresh`, they are very different ...
=> important fix typo 

docs/index.md, docs/quickstart/existing_dataset.md
Add a new documentation page describing some existing datasets, to help improve discoverability and make it easier to compare different options.
There are a few minor things I wanted to do but wasn't able to figure out, which I'd appreciate guidance on:
* How to make a reference to the automatically generated `reference/cli/ns-download-data.html`, rather than hardcoding in a link to the online version (line 5).
* How to have a reference to another heading, so that the "Image Count<sup>1</sup>" and "Image Resolution<sup>2</sup>" table headings in the summary table can directly link to the larger tables at the bottom. The standard markdown syntax didn't seem to work here, and I couldn't get the [explicit targets](https://myst-parser.readthedocs.io/en/latest/syntax/cross-referencing.html#crea …
=> Add documentation on existing datasets

nerfstudio/scripts/downloads/download_data.py
I ran into a few issues while running the various download commands on my Windows box. This diff attempts to remedy those issues. In no particular order:
* Switching from `os.system` to `subprocess.run` calls, which have better handling of `'` vs `"` and other shell escapes. In particular, the `'` which were previously used (line 431) weren't working in CMD, which is used by `os.system` on my machine. They work fine in powershell, though.
* Updated `curl` call to use `-o` flag to directly output to file, rather than going through IO redirection.
* Updated all download functions to use unique temp directories, rather than sharing `.temp`. This allows multiple download jobs to run concurrently, since they're typically rate-limited by the upstream.
* More informative error message for when …
=> Make downloading more windows-friendly

nerfstudio/scripts/render.py
This fixes 
```
ValueError: mutable default <class 'nerfstudio.data.scene_box.OrientedBox'> for field obb is not allowed: use default_factory
```
=> Fix "mutable default" error in render.py

colab/demo.ipynb
in the demo colab notebook, `gdown` is unable to install `colmap` because the gdrive link is not sharable or not available. 
This issue is also mentioned here:
1. https://github.com/nerfstudio-project/nerfstudio/pull/2787/files
- `!conda install -c conda-forge colmap` will raise a `PackagesNotFoundError`.
2. https://github.com/nerfstudio-project/nerfstudio/issues/2406#issuecomment-1746746583
- the fix mentioned here will also have a `PackagesNotFoundError` and then the runtime always crashes/restarts
To download colmap, using `apt-get` solved these issues and allowed me to process my data in the following cell - it is a quick one-line and it takes about 4minutes 16seconds to install nerfstudio and its dependencies
=> fixing colmap installation to use apt-get since gdown on the URL unable to download colmap

colab/demo.ipynb, nerfstudio/models/splatfacto.py
Set default bg to viser color in gs to fix strange bg color in rendering.
=> Fix the background color bug when exporting video with the "random" background option

nerfstudio/configs/method_configs.py, nerfstudio/fields/density_fields.py, nerfstudio/fields/nerfacto_field.py, nerfstudio/models/nerfacto.py
This has been my personal recipe for training nerfacto: the basic issue of current nerfacto implementation is the scene is always initialized with an average density at 1.0 (due to the exponential activation of MLP). This is not a robust choice in general especially when scene depth is much higher than 1.0. 
One famous example is the mipnerf360 `stump` dataset, when training with the recommended setting before this PR
```
ns-train nerfacto --data stump \
--pipeline.model.appearance_embed_dim 1 \
--pipeline.model.camera_optimizer.mode off
```
The PSNR on eval set is only 18. With this PR, one can choose to train with a multiplier on top of density output. My personal experience is to set it 0.01 so the scene is very transparent initially. 
```
ns-train nerfacto --data stump \ …
```
=> Add average_init_density to improve robustness of nerfacto training

pyproject.toml
Because of https://github.com/pytorch/pytorch/issues/118736, our build actions are failing. Hopefully this fixes it
=> limit torch to <=2.1 to avoid type errors

nerfstudio/models/depth_nerfacto.py
In direct depth supervision methods, calling `depth_loss` will not work unless we can compute gradients on the predicted depth. The predicted depth right now is a median and there are no gradients that can be computed. I have changed it to expected depth to allow direct depth supervision methods to work.
=> Have predicted depth as expected_depth so gradients can be computed

nerfstudio/configs/method_configs.py
I found many users in discord complains about OOM error when training with > 1000 images. We probably need to enable this option by default in the `method_configs`.
=> Avoid OOM for caching undistorted images of splatfacto

nerfstudio/process_data/odm_utils.py, nerfstudio/scripts/process_data.py
Hello :wave:
I made a mistake in #2838 and while processing a different dataset I noticed an issue with the coordinate system conversion I wrote.
I tested these changes with multiple datasets and they work now.
Link to datasets exported with proposed change: https://drive.google.com/drive/folders/1tmeBSlLcUJKxpwqhFC2YqqSGUKlGoMtN?usp=sharing
=> Fix ODM data processor coordinate system

nerfstudio/process_data/process_data_utils.py
`ns-process-data` produces pixelated downscaled images.
Original:
Downscale by a factor of 2:
The current implementation only applies `-q:v 2` to the original images. Placing `-q:v 2` before all the outputs fixes the issue.
Downscale by a factor of 2:
=> fix: pixelated downscaled images

nerfstudio/models/splatfacto.py
I'm working on some depth losses, and having this functionality to always return depth, even during training, would be very useful for cleanliness in my codebase.
=> Enable always returning depth for Gaussian Splatting

README.md, docs/developer_guides/viewer/local_viewer.md
Some of the language in the docs was only relevant for the legacy version of the viewer.
(unrelated, but I also tweaked the discord badge in the README)
Addresses #2869
=> Update viewer legacy docs

nerfstudio/models/splatfacto.py
There should be a default `"depth"` value returned alongside `"rgb"`, or the renderer may crash if there is no gaussians in the front.
More specifically, L173 and L189 will currently crash in nerfstudio if `"depth"` is undefined:
https://github.com/nerfstudio-project/nerfstudio/blob/52cda21186a9a50b29e7480d3dec20b5b15323d3/nerfstudio/viewer/render_state_machine.py#L170-L191
=> Add default depth output when no gaussians visible

nerfstudio/scripts/render.py
Fixes https://github.com/nerfstudio-project/nerfstudio/issues/2881
=> Remove useless call to .with_suffix(""), which causes a bug if filename contains dots

nerfstudio/cameras/camera_optimizers.py
Add a conversion of the camera index to tensor as the forward function expects `Int[Tensor, "camera_indices"]` as input.
=> [Fix] convert camera_idx to tensor

docs/index.md, docs/nerfology/methods/index.md, docs/nerfology/methods/zipnerf.md, nerfstudio/configs/external_methods.py
Add zipnerf-pytorch to the documentation as an external method. 
I’ve submitted a [PR](https://github.com/SuLvXiangXin/zipnerf-pytorch/pull/98) to the [original zipnerf pytorch repo](https://github.com/SuLvXiangXin/zipnerf-pytorch) to support nerfstudio. I'll update link in docs if its merged.
=> add zipnerf-pytorch as external method

nerfstudio/models/splatfacto.py
This PR is similar in spirit to https://github.com/nerfstudio-project/nerfstudio/pull/2165 and https://github.com/nerfstudio-project/nerfstudio/pull/2025 for Nerfacto.
It implements the transparency trick which allows to carve a gaussian splatting scene when the masks are known.
The process is well described by the aforementioned PR:
> 
1. Make everything except for the foreground object transparent in each image.
2. While rendering, pick a random color in each iteration, then use this random color as background during alpha compositing.
3. When computing the RGB loss, make the color of transparent pixels match the randomly chosen color of the current iteration used for rendering.
Here is a comparison before/after on the lego scene from the Nerf Blender dataset: …
=> Add transparency carving to splatfacto

nerfstudio/engine/trainer.py
As discussed on Discord (Thanks Brent), `--gradient-accumulation-steps` did not properly cast its values to int and would error because it received a string.
There is still a separate bug where specifying `camera_opt` on nerfacto will cause an error, and the documentation on the --gradient-accumulation-steps could be better (accepted values are currently `proposal_networks`, `fields` and `camera_opts`, but there's no way to figure this out without without diving into the code AFAICT), but that's for another time/person/PR.
=> Fix an issue where gradient accumulation could not be passed as argument due to a type error.

nerfstudio/models/splatfacto.py, pyproject.toml
See previous threads here: https://github.com/nerfstudio-project/gsplat/pull/117
The PR must be merged after this PR (version bump of gsplat lib, https://github.com/nerfstudio-project/gsplat/pull/124)
=> Implement new rasterization mode using opacity compensation factor

nerfstudio/models/splatfacto.py
Hello :wave:
While looking through the splatfacto implementation, I noticed that in the case of an early exit in the forward pass due to a zero radii sum the camera does not get rescaled back to its original dimensions. I think this might be a mistake? I haven't found a dataset where the condition occurs, but it seems correct to make sure the camera is rescaled back before returning.
=> Call rescale_output_resolution before early return

nerfstudio/viewer/render_state_machine.py, nerfstudio/viewer/utils.py
This pull request makes the time slider in the Control panel of the viser viewer effective again, for dynamic models.
The Render panel still misses options to set a per-keyframe timestamp, but I will probably do it in a separate PR. This should do the job for now to monitor training.
For those interested, meanwhile, you can use the legacy viewer (`--vis viewer_legacy`) to create camera paths for dynamic scenes.
=> Make time slider effective in viewer (Fixes #2928)

nerfstudio/models/splatfacto.py, pyproject.toml
In gsplat==0.1.6, the interface for tile_bounds is replaced by simply specifying a block size.
=> Update project, rasterize with block_width interface

nerfstudio/viewer/render_panel.py, nerfstudio/viewer/render_state_machine.py, nerfstudio/viewer/utils.py, nerfstudio/viewer/viewer.py
This pull request finalizes the feature fix in PR #2931.
To allow working with dynamic scenes on the new Viser viewer, the *Render* panel now allows for setting per-keyframe timestamps along with a default time value. When rendering, it will interpolate between the times of each keyframe (similar to FOV interpolation).
Also, unlike the legacy viewer which does not support previewing the dynamic render, this PR separates the default view (using the time in the Control panel) and the preview view so that one can preview (although blurry obviously :-)) their rendered dynamic scene!
- The Control panel now has a slider for setting the time at which the (dynamic) scene is rendered.
- The Render panel now has a default time slider, which sets the default time for each keyframe.
- Each keyframe …
=> Full implementation of features for dynamic scenes into the Viser viewer.

nerfstudio/models/splatfacto.py
Splatfacto crashes when mask is exist and num_downscale > 0, because downscale has not been applied to mask.
=> fix crash when both mask and downscale_factor are set

nerfstudio/data/pixel_samplers.py
#2783 fixed an issue where the `fisheye_crop_radius` metadata field was being accidentally deleted. Unfortunately this also broke `nerfacto` support for Aria, since it exposed some broken fisheye sampling logic from #2617 (which was previously not being run).
Specific fixed problems:
- Sampled x/y coordinates were unnecessarily scaled by `image_height // 2` and `image_width // 2`, since the crop radius is already in pixel units.
- The circle crop typically exceeds the bounds of the image, so sampling from the circle naively still has issues. We fix this with rejection sampling.
These changes + #2783 reduce artifacts.
Before:
https://github.com/nerfstudio-project/nerfstudio/assets/6992947/7c28e9ee-fa9d-4c4c-812f-cf38fa148de7
After: …
=> Fix Nerfacto + Aria

nerfstudio/data/datamanagers/full_images_datamanager.py
I think the progress bar broke in #2867.
I also dropped `max_workers` for the thread pool to 2, since the OpenCV undistortion that it calls is already multi-threaded.
=> Fix progress bar for full images datamanager

nerfstudio/models/splatfacto.py
fix bug that opacity compentation has not being applied to depth raterization, found from @jb-ye 's new rasterization mode implementation pr
https://github.com/nerfstudio-project/nerfstudio/pull/2888#issuecomment-1961824489
=> fix bug that opacity compentation not being applied to depth raterization

docs/nerfology/methods/splat.md
Add splatfacto-big to the docs
=> add splatfacto-big docs

nerfstudio/configs/method_configs.py, nerfstudio/models/splatfacto.py
This simplifies subclassing, and simplifies some of the logic for culling/splitting.
=> Refactor splatfacto gaussian params with a ParameterDict

docs/nerfology/methods/nerf.md
In NeRF methods doc, old code component was found. So just fix this small typo issue.
Current one:
```python
from nerfstudio.renderers.renderers import RGBRenderer
```
Correct one:
```python
from nerfstudio.model_components.renderers import RGBRenderer
```
Thanks for reviewing!
=> doc: fix code typo in 'NeRF' method doc

nerfstudio/cameras/camera_optimizers.py, nerfstudio/data/pixel_samplers.py
Depth nerfacto doesn't work unless num_rays_in_batch is divisible by 2. Also, the depth images are in a list and not just a batch tensor, so I think the changes I made are needed.
=> Fix depth-nerfacto edge cases

nerfstudio/models/instant_ngp.py, nerfstudio/models/tensorf.py
instant-ngp and tensorf models are currently not handling training on transparent images properly as other models do, resulting in worse performance on synthetic datasets.
Currently, the alpha channel is simply being removed which prevents proper handling of background rendering which `blend_background_for_loss_computation` is supposed to handle for support of rendering random background color during training etc.
This PR just changes the code to pass the full image to be consistent with other models: 
https://github.com/nerfstudio-project/nerfstudio/blob/3a4ed804d3abe1565ccd521247a2724b68ee28e2/nerfstudio/models/nerfacto.py#L365
https://github.com/nerfstudio-project/nerfstudio/blob/3a4ed804d3abe1565ccd521247a2724b68ee28e2/nerfstudio/models/mipnerf.py#L145
=> Handle alpha images properly for instant-ngp and tensorf models

nerfstudio/data/datamanagers/full_images_datamanager.py
I noticed that masks in splatfacto are not working after undistortion. I get an error when masks are applied in the full images datamanager in line 881 (gt_img = gt_img * mask) as the shapes are (w, h, 3) and (w, h), however they need to be (w, h, 3) and (w, h, 1).
The resulting Error is: RuntimeError: The size of tensor a (3) must match the size of tensor b (3839) at non-singleton dimension 2
terminate called without an active exception
Please note that this issue is not present in nerfacto. Also it does not appear when using undistorted images (k- and p-params all 0)
I fixed it by adding the third dimension after undistortion. Tested both splatfacto and nerfacto as well, seems to be fixed to me.
=> Fix: Masks having wrong dimension after undistortion (causes crash in splatfacto)

nerfstudio/process_data/colmap_converter_to_nerfstudio_dataset.py, nerfstudio/process_data/process_data_utils.py
delete space "simple_pinhole": CameraModel.SIMPLE_PINHOLE,
=> Camera models

pyproject.toml
When I try to run:
```console
$ pip install -e .[gen,dev,docs]
...
ERROR: Cannot install None, nerfstudio[dev,docs,gen]==1.0.2 and open3d==0.18.0 because these package versions have conflicting dependencies.
The conflict is caused by:
nerfstudio[dev,docs,gen] 1.0.2 depends on nbformat==5.5.0; extra == "docs"
myst-nb 0.16.0 depends on nbformat~=5.0
nbconvert 7.2.5 depends on nbformat>=5.1
open3d 0.18.0 depends on nbformat>=5.7.0
```
This gets fixed by upgrading to the latest `nbformat`: https://pypi.org/project/nbformat/5.9.2/#history
=> Upgrade to latest nbformat 5.9.2

nerfstudio/scripts/exporter.py
Fixes nerfstudio-project/nerfstudio#3004
I could not figure a clean way to do it with the open3d library.
The ply file produced by this patch has been verified to be loadable by aras-p/UnityGaussianSplatting and antimatter15/splat
=> Make ply export property ordering backward compatible (fixes nerfstudio-project/nerfstudio#3004)

nerfstudio/cameras/camera_utils.py
When tensors a and b are float32, the condition c < -1 + 1e-8 will never be triggered because of round off tolerance being too small. Also I use a more principled implementation for computing the rotation matrix when a, b are opposite. 
Test cases:
```
a=torch.rand(3, dtype=torch.float32)
b=-a
error=torch.norm(rotation_matrix(a, b) @ a[..., None] - b[..., None])
```
=> Fix rotation_matrix for opposite float32 vectors

nerfstudio/viewer/render_panel.py
This PR fixes the issue that I see when trying to add multiple keyframes in the viewer to generate a camera path for rendering. I get the following error:
```
File "repos/nerfstudio/nerfstudio/viewer/render_panel.py", line 269, in spline_t_from_t_sec                                                                                                             interpolator = scipy.interpolate.PchipInterpolator(                                                                                                                                                            
AttributeError: module 'scipy' has no attribute 'interpolate'  
```
FYI, I don't see this error when trying to create a camera path running the legacy viewer i.e. when I try to create a path after running `ns-viewer --load-config …
=> Fix bug when trying to create a camera path in viewer

docs/developer_guides/viewer/viewer_control.md, nerfstudio/viewer/viewer_elements.py, pyproject.toml
Related to rect-select viser PR, linked here: https://github.com/nerfstudio-project/viser/pull/157. 
This adds `ViewerRectSelect`, a rectangular selection in 2D parameterized by its min/max bounds. This PR also adds `screen_pos` property to `ViewerClick`, the screen position associated with the click.
There's many exciting applications for this -- especially in splatfacto, where we can select groups of gaussians. One example is #3001, for floater removal (@anniezhang2288 :) )
The example video shows both interaction types, clicking and rectangular selection. More specifically, for the rectangular selection, the video shows:
* how gaussians can be selected -- only keeping the gaussians that project inside the selection box.
* ... and what happens if you continue training. …
=> Support rectangle selection in viewer

nerfstudio/models/splatfacto.py, pyproject.toml
Requires https://github.com/nerfstudio-project/gsplat/pull/97
=> Get rid of redundant projection matrix computations in Splatfacto (needs a gsplat update)

nerfstudio/data/datasets/base_dataset.py, nerfstudio/data/utils/data_utils.py, pyproject.toml
The latest version update of Pillow will break nerfstudio since it is using a deprecated API field.
=> Fix core tests with Pillow>=10.3.0

nerfstudio/process_data/images_to_nerfstudio_dataset.py, nerfstudio/process_data/process_data_utils.py, tests/process_data/test_process_images.py
The code was previously looking for the file.name, which drops all directory information from the path. Instead, we want to get the file path relative to the data dir, which will only drop parts of the path above the data dir, allowing us to recurse into subdirectories within the images dir
For example, you can use COLMAP reconstructions that were built using multiple captures and have an images directory structured like this:
```
images
└── DJI_0238
├── 000000.jpg
├── 000041.jpg
├── 000060.jpg
└── DJI_0286
├── 000000.jpg
├── 000041.jpg
├── 000060.jpg
```
=> Support COLMAP reconstructions with non-flat image dirs

docs/developer_guides/viewer/viewer_control.md, nerfstudio/viewer/viewer_elements.py, pyproject.toml
For https://github.com/nerfstudio-project/viser/pull/196 .
- Update docs.
- Rename `done_cb` --> `removed_cb`.
- Bump `viser` to `0.1.27`.
=> Refactor ScenePointerCallbacks for viser compatibility

nerfstudio/data/datamanagers/full_images_datamanager.py, nerfstudio/viewer/utils.py
Some changes to only undistort splatfacto train/eval images when they're used. This should speed up:
- `ns-export`
- `ns-render`: fixes #2971
- `ns-viewer` with `--viewer.max-num-display-images 0`: fixes #2817
=> Only load+undistort splatfacto images when they're used

nerfstudio/cameras/cameras.py, nerfstudio/data/dataparsers/colmap_dataparser.py
In order to be compatible with the original format of the 360_v2 dataset without reprocessing it, I added an option to colmapDataParser to round up the image size when downscaling. This may change the image height and width in the camera.
But I'm not sure if it will have any negative impact on other parts?  If so, please let me know. Thank you!
=> Make colmapDataParser compatible with 360_v2 dataset format

nerfstudio/scripts/downloads/eyeful_tower.py
Support for the Eyeful Tower dataset in Nerfstudio was added earlier this year and it mostly works well. However, when trying to load a checkpoint for this dataset using config.yml (either with ns-viewer or ns-render), an error message shows up.
`ns-viewer --load-config outputs/images-jpeg-1k/nerfacto/2024-04-06_181030/config.yml`
> RuntimeError: The dataset's list of filenames for split test is missing
Since there is no specific test set for this dataset, having an empty "test_filenames" entry in the transforms.json seems to be enough to deal with this issue. This PR adds a single line of code making this change.
=> Fix config loading for Eyeful Tower dataset

nerfstudio/scripts/exporter.py
Just added the imports and assertions for solving the Generfacto case. 
This is fixing this issue:
https://github.com/nerfstudio-project/nerfstudio/issues/2121
=> fix exporter.py for FullImageDataManager and RandomCamerasDataManager

nerfstudio/cameras/camera_optimizers.py, nerfstudio/configs/method_configs.py, nerfstudio/models/splatfacto.py
_Updated description, April 7_: Camera pose optimization for Splatfacto, based on https://github.com/nerfstudio-project/gsplat/pull/127, which is included in gsplat 0.1.9+. See https://github.com/nerfstudio-project/nerfstudio/pull/2891#issuecomment-2041027334 for instructions and examples.
.
_Original description, outdated:_ ~This PR is intended as an extension of https://github.com/nerfstudio-project/nerfstudio/pull/2885, but I could not easily create a PR to that branch, so creating a new PR instead. A detailed description in a comment in the original PR: https://github.com/nerfstudio-project/nerfstudio/pull/2885#issuecomment-1936410849~
~@jh-surh : Feel free to merge / cherry-pick any of my commits in this branch to your original PR, [...]~
=> Camera pose optimization for Splatfacto

docs/quickstart/data_conventions.md, nerfstudio/data/datamanagers/full_images_datamanager.py
addresses https://github.com/nerfstudio-project/nerfstudio/issues/3048
=> shift principle points by .5 in undistortion

nerfstudio/data/dataparsers/blender_dataparser.py
It is a simple change such that user can use the following commands to do [alpha transparency](https://github.com/nerfstudio-project/nerfstudio/pull/2889) training on blender dataset:
```
ns-train splatfacto-big --data materials/ \
--pipeline.model.background-color random \
--pipeline.model.random_scale 2.6 \
--logging.local-writer.max-log-size=0 \
blender-data --alpha_color=None
```
=> Allow alpha transparency training for blender datasets input

nerfstudio/process_data/colmap_converter_to_nerfstudio_dataset.py, nerfstudio/process_data/colmap_utils.py, nerfstudio/process_data/hloc_utils.py
Hloc gets a single image_ids [here](https://github.com/cvg/Hierarchical-Localization/blob/master/hloc/reconstruction.py#L129) so that it is unable to get the matching between images. Thus it gets an error on not finding images "frame_XXX not found". This little fix in `hloc_utils.py` is solving this issue https://github.com/nerfstudio-project/nerfstudio/issues/3059
Found this error on using `--no_same_dimensions` with `disk` features and `disk+lightglue` matching
=> Hloc fix for image_ids (camera per image)

nerfstudio/scripts/viewer/run_viewer.py, nerfstudio/viewer/viewer.py
I added a wrapper around the viser element callback so the render thread is blocked while the callback is called to avoid crashing. I also added a lock in run_viewer.py so this issue is addressed for both ns-train and ns-viewer. 
Test: I added time.sleep() in the callback and confirmed the render thread was blocked.
=> Adding lock for Viser Element callbacks

nerfstudio/exporter/exporter_utils.py, nerfstudio/scripts/exporter.py, nerfstudio/viewer/export_panel.py
- Enabled obb in the viewer command generation
- Added obb support in the export
=> Adding cropping for gaussian splat exports

nerfstudio/configs/method_configs.py, nerfstudio/models/splatfacto.py, pyproject.toml
I am following the parameter setting as recommended in https://arxiv.org/pdf/2404.10484
In order to experiment this PR, one need to install the customized gsplat library as in this PR https://github.com/nerfstudio-project/gsplat/pull/166
```
pip install git+https://github.com/nerfstudio-project/gsplat.git@absgrad
pip install git+https://github.com/jb-ye/nerfstudio
```
I will follow up my experiments here. I recommend to experiment with one of the two settings (A, B) and use input image resolution higher than 1600 (e.g. 2k or 4k)
O splatfacto-big in latest main branch (--rasterize_mode antialiased)
A splatfacto-big of this PR (--rasterize_mode antialiased --densify_grad_thresh=0.0008)
B splatfacto-big of this PR (--rasterize_mode antialiased --densify_grad_thresh=0.0004)
O. baseline.
A. …
=> Use AbsGrad to get better results with less gaussians

nerfstudio/data/pixel_samplers.py, nerfstudio/data/utils/pixel_sampling_utils.py
Current sampling will oversample the first (num_images - 1) images, and might return a negative number of rays for the last image. The proposed fix finds an optimal ratio of rays per image such that the constraint of always being divisible by 2 is still satisfied.
=> Fix bug in pixel sampler

nerfstudio/models/splatfacto.py, nerfstudio/process_data/metashape_utils.py, nerfstudio/scripts/process_data.py
test commands:
```
ns-process-data metashape --xml floorboard.xml --data floorboard/ --ply floorboard.ply --output-dir floorboard_nerfstudio/
```
=> Support splatfacto training for metashape exports

nerfstudio/data/utils/nerfstudio_collate.py
This fixes the nerfstudio collate function in cases where metadata, distortion, or times isn't specified in the cameras structure to collate.
=> fix nerfstudio collate function

nerfstudio/data/datamanagers/full_images_datamanager.py, nerfstudio/process_data/realitycapture_utils.py, nerfstudio/scripts/process_data.py
fix #3118 
Changes in this PR:
1. fix cx,cy calculation which was done wrong previously
2. add --ply option to `ns-process-data realitycapture` to support splatfacto
3. safeguard brown4 tangential2 distortion model in full data manager, since opencv's undistort doesn't support it.
=> Make RealityCapture csv/ply exports work!

nerfstudio/utils/colormaps.py
If the user sets near_plane as 0.0, the "or" will take the second term (float(torch.min(depth))) instead of using the 0.0 value.  We fix this by checking explicitely for a "None" variable
=> Fix edge case of depth colormap

nerfstudio/data/datamanagers/full_images_datamanager.py
Currently, [next_eval](https://github.com/nerfstudio-project/nerfstudio/blob/8d5502db1a599c1ccb68807aa364482a931fb60c/nerfstudio/data/datamanagers/full_images_datamanager.py#L306) and [next_eval_image](https://github.com/nerfstudio-project/nerfstudio/blob/8d5502db1a599c1ccb68807aa364482a931fb60c/nerfstudio/data/datamanagers/full_images_datamanager.py#L320) in the [full_images_datamanager.py](https://github.com/nerfstudio-project/nerfstudio/blob/8d5502db1a599c1ccb68807aa364482a931fb60c/nerfstudio/data/datamanagers/full_images_datamanager.py) do exactly the same in a redundant fashion.
As both function's might be used, to reduce the redundancy, I made one function call the other.
=> remove redundant code in full_images_datamanager.py

nerfstudio/data/datamanagers/full_images_datamanager.py, nerfstudio/models/splatfacto.py
There is a runtime error when boolean masks are fed into `splatfacto`: (For me, this happened when testing with aria data)
Additionally, when the distortion parameters are all 0 (meaning there is no distortion in the image), splatfacto will still try to distort the image because `distortion_params` are not None, so adding a quick check on that prevents images from being fed to the undistort function when there is no distortion.
=> Fixing resize_image and adding additional distortion check

docs/index.md, docs/nerfology/methods/index.md, docs/nerfology/methods/nerf2gs2nerf.md, nerfstudio/configs/external_methods.py
It contains the updates to include NeRFtoGSandBack ([https://arxiv.org/abs/2405.09717](https://arxiv.org/abs/2405.09717)) in nerfstudio. Thanks for your time in advance!
=> NeRFtoGSandBack

nerfstudio/data/datamanagers/full_images_datamanager.py, pyproject.toml
Currently, the train cameras are sampled uniformly random without replacement in full_images_manager. There are cases when one wants to implement a different camera sampler other than uniformly random sampler. For example, this PR implements a type of sampler as an alternative option that can avoid oversampling cameras that are very close to each other (using farthest distance sampling), because I observed that oversampling train cameras from very similar views can potential create unwanted floaters. 
Choosing an optimal distribution over a given set of cameras to train is a non-trivial problem and have been discussed in literature (e.g. https://arxiv.org/pdf/2109.02369 ). But this topic goes beyond the scope of this PR. 
This PR also fixed the seed of train camera sampler for improving …
=> Introduce FPSampler for train cameras

pyproject.toml
@liruilong940607 @maturk  Apparently the new 1.0 release has API-breaking changes, which breaks fresh installs, as observed in discord https://discord.com/channels/1025504971606724712/1167872346707738664/1248794449148907644
i guess yall drafting an update ( https://github.com/nerfstudio-project/nerfstudio/tree/gsplatv1.0 ) but does not appear to be in PR yet.  so mebbe wanna fix `main` with this patch for now?
=> Ignore gsplat 1.0 for now

docs/nerfology/methods/splat.md, nerfstudio/configs/method_configs.py, nerfstudio/data/datamanagers/full_images_datamanager.py, nerfstudio/models/splatfacto.py, nerfstudio/scripts/process_data.py, pyproject.toml
- Pin dependence to `gsplat==1.0.0`
- A few slight improvements on splatfacto model and its data loading, by @kerrj 
This is a hot fix as the `pip install nerfstudio` would be failing currently because of #3197  so we need to bump a version that either pins to `gsplat==1.0.0` or pins to `gsplat <=1.0.0` asap.
=> Update splatfacto with gsplat 1.0

nerfstudio/models/splatfacto.py
Fix the issue of `torch.compile()` introduced in #3200 is not supported on windows
=> torch.compile -> torch_compile from misc

nerfstudio/process_data/colmap_converter_to_nerfstudio_dataset.py, nerfstudio/utils/install_checks.py
check_colmap_installed() in nerfstudio.utils.install_checks.py previously didn't use the colmap_cmd attribute of ColmapConverterToNerfstudioDataset. This change addresses that so an alternative colmap_cmd can actually be used. This addresses issue #3195
=> Making install_checks use colmap_cmd

nerfstudio/models/splatfacto.py
=> Fix bug in SplatfactoModel when sh_degree is zero the color is not with sigmoid

nerfstudio/models/splatfacto.py
In the `_get_background_color()` function in splatfacto.py, `self.background_color` is allocated on the cpu, when calling `get_outputs()`, we get a runtime error "RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!". Added a `.to(self.device)` to ensure this doesn't happen
=> Small fix when evaluating splatfacto model, running ns-eval

nerfstudio/data/utils/colmap_parsing_utils.py
If colmap image file name is non ascii an error will be thrown in the line `current_char.decode("utf-8")` while trying to parse the file `images.bin`
It is thrown because it tries to decode a single byte as `utf-8`, And non ascii chars are represented using more bytes than 1.
My solution proposal is to read all the bytes, and than decode it.
I tested it and it worked OK
=> Fix parsing of non ascii image names in colmap's images.bin

Dockerfile
Update pytorch to fix gsplat incompatibilities with versions >= 1.0.0
Additionally, version pinning of tinycudann as 1.6 was removed as it is not compatible with the new pytorch
setuptools is now fixed to 69.5.1 also because of incompatibilities
Currently, numpy 2 creates an error but as others are already working on fixing this in nerfstudio I'm skipping it in the Dockerfile. In case you need to fix it now please pin the version in nerfstudio dependencies or add a line in the Dockerfile before the ns-install-cli command:
RUN python3.10 -m pip install --no-cache-dir numpy==1.26.4
Fixes #3235
=> Update pytorch in Dockerfile to 2.1.2

nerfstudio/data/dataparsers/colmap_dataparser.py
**Issue**: When running `splatfacto` with my custom dataset of images with varying resolutions, I encountered a dimension mismatch error between the downscaled cameras and images. This issue arises because the `_downscale_images` function in `colmap_dataparser.py` ([L484](https://github.com/nerfstudio-project/nerfstudio/blob/main/nerfstudio/data/dataparsers/colmap_dataparser.py#L484)) uses a fixed downscaling size for every image.
**Proposed Solution**: Modify `_downscale_images` to compute the downscaling size individually for each image to ensure compatibility with images of different resolutions.
=> Fix dimension mismatch between downscaled cameras and images in colmap.

docs/quickstart/existing_dataset.md, nerfstudio/scripts/downloads/download_data.py, nerfstudio/scripts/downloads/eyeful_tower.py, pyproject.toml
As discussed in #3269, removes `awscli` from the main project dependencies in favor of a manual install by Eyeful Tower users. 
Main changes:
* Removes `awscli` from `pyproject.toml`.
* Adds error handling on `eyefultower.py` prompting users to install `awscli` on `ImportError`. 
* Adds error handling to `download_data.py` for case when `awscli` is not installed.
* Adds lines to documentation instructing Eyeful Tower users to manually install `awscli`.
=> Make `awscli` an optional dependency

docs/quickstart/installation.md
There was some vital information missing from the Pixi installation instructions. It still isn't perfect, but this PR adds the most critical information to get people going with hopefully less frustration, without blowing up the scope/size too much.
=> Update installation.md: Add missing Pixi documentation

nerfstudio/pipelines/base_pipeline.py
Loose assert condition for datamanger in get_average_eval_image_metrics(). This enables external methods with modified datamangers to use VanillaPipeline.
=> Loose assert condition for datamanger in get_average_eval_image_metrics()

nerfstudio/viewer/utils.py, nerfstudio/viewer/viewer.py
Allows viser to pass the last clicked camera idx to the get_camera_output function.
=> Pass current camera idx in metadata to get output from viser

pyproject.toml
Related issues: #1223 and #2179
Currently, Nerfstudio/colmap depends on specific GUI libraries to be installed/available, even on headless systems.
Is there any reason to not simply swap out opencv-python for opencv-python-headless? 
I don't think there's anything Nerfstudio does that relies on running a GUI locally, directly, and swapping it out for `-headless` seems to have worked for a number of people.
I would think most headless Linux systems would be affected, though mine are too "contaminated" to confirm.  
At the very least, WSL2 Ubuntu is affected, as it does not ship with these GUI libraries.
Fixes issues like this on headless Linux/WSL2 installations:
```
[01:43:53] 🎉 Done converting video to images.                                                 process_data_utils.py:219
── …
```
=> Swap out opencv-python for opencv-python-headless

nerfstudio/cameras/camera_utils.py
Parameter copy in np.array
in [version 2.0](https://numpy.org/doc/stable/reference/generated/numpy.array.html):
copy:bool, optional
If True (default), then the array data is copied. If None, a copy will only be made if __array__ returns a copy, if obj is a nested sequence, or if a copy is needed to satisfy any of the other requirements (dtype, order, etc.). Note that any copy of the data is shallow, i.e., for arrays with object dtype, the new array will point to the same objects. See Examples for [ndarray.copy](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.copy.html#numpy.ndarray.copy). For False it raises a ValueError if a copy cannot be avoided. Default: True.
in [version 1.x](https://numpy.org/doc/1.26/reference/generated/numpy.array.html):
copybool, optional
If true …
=> make np.array compatible with numpy 2.0

nerfstudio/data/dataparsers/blender_dataparser.py
I'm following this reference code to improve the speed of importing the Blender DataParser. We should only import Open3D when we need it.
https://github.com/nerfstudio-project/nerfstudio/blob/b0dd3d473094fb0942b357ef436b362df1ef77cd/nerfstudio/data/dataparsers/scannet_dataparser.py#L207
=> Lazy import for open3d in Blender DataParser

nerfstudio/data/datamanagers/full_images_datamanager.py
I think this should fix #3335; cc @kerrj @jb-ye @AntonioMacaronio
=> Fix memory leak in full_images_datamanager.py

nerfstudio/models/splatfacto.py
gsplat is gonna to deprecate `.cuda_legacy`
=> get rid of gsplat legacy dep

nerfstudio/data/datamanagers/full_images_datamanager.py
**Problems and Background**
- When an image is undistorted by OpenCV's `undistort` for perspective cameras, there could be a returned Region-Of-Interest (ROI) where the image's pixels are well defined.
- Nerfstudio does crop the image according to OpenCV's returned ROI, but it does not update the camera intrinsics to reflect where the new principal point has shifted, (usually the crop is very tiny <= 1 pixel or doesn't exist at all) so this isn't that noticeable.
**Overview of Changes**
- Added some notes explaining the processing to use OpenCV
- Fixed the updated principal points in the returned intrinsic matrix
=> Updating camera intrinsics (principal points) when the undistorted image is cropped

nerfstudio/models/splatfacto.py, nerfstudio/scripts/exporter.py
=> Update exporter.py to export sh_degree 0 case #3371

nerfstudio/cameras/cameras.py
Training with mixed batches of camera types seems to be broken. The camera types are looped over, but the same type will trigger the if/else each time through the loop in its current form, leaving uninitialized rays for the other camera types.
This MR fixes that, enabling support for mixed batches of rays.  My guess is this was the original intent of the code.
=> bugfix: handle multiple camera types in a single batch

nerfstudio/engine/trainer.py, nerfstudio/viewer/viewer.py, nerfstudio/viewer_legacy/server/viewer_state.py
`--start_paused` option for `ns-train` to set initial training state as paused
Closes #3358
=> Add option to start training paused

nerfstudio/configs/method_configs.py, nerfstudio/models/splatfacto.py, nerfstudio/scripts/exporter.py, pyproject.toml
Given the latest updates of gsplat strategy interface, it is of interest to use the feature to benefit from multiple strategy implementations provided. The first step is to refactor existing splatfacto code meanwhile maintain the performance of current splafacto-big.
I spent some time debugging current gsplat implementation and found that we need to first merge [this fix](https://github.com/nerfstudio-project/gsplat/pull/358) in order to reproduce the performance of current splatfacto-big. We don't necessarily need to merge the fix, this is just for producing baselines. 
To benchmark simple_trainer.py in splatfacto configuration:
```
python simple_trainer.py default --data_dir bicycle/ \
--strategy.absgrad \
--strategy.grow_grad2d 0.0006 \
--strategy.prune_scale3d 0.5 \ …
```
=> use gsplat strategy interface to simplify splatfacto

nerfstudio/scripts/exporter.py
Since Gaussian Splat ply generation doesn't require the dataset data it can be generated from inference mode reducing memory and allows the export even if the initial dataset is lost.
=> Minor update to generate splat files in inference mode

nerfstudio/exporter/exporter_utils.py
The same mask was used twice when `crop_obb` was None. This led to indexing errors.
I would provide example data but it should make sense when reading the code from line `158`.
=> Fix crop obb masking in pointcloud generation

nerfstudio/process_data/process_data_utils.py, nerfstudio/process_data/video_to_nerfstudio_dataset.py, tests/process_data/test_misc.py
This PR relates to the Issue [#3048](https://github.com/nerfstudio-project/nerfstudio/issues/3408)
Background: Currently, frame processing video logic works by sampling N frames from N evenly spaced intervals throughout the video. Although a worthy method, researchers should be allowed to choose frames from a random seed to produce more consistent results. 
This PR implements optional --random_seed and --eval_random_seed flags for the ns-process-data video in case a specific seed is requested.
Verification Evidence: Placed a video and a random seed to produce a consistent result
Here is the result
1) Showing that the same seed will process the same image frames
2) Showing the 50-frame output of the set 
3) Showing that the original frame split works successfully
[
](URL)
Unit Tests: A …
=> Adding Random Seed for Frame Processing

nerfstudio/engine/trainer.py
This addresses the issue in #3253 where splatfacto training could crash during the evaluation step when interacting with the viewer (e.g., with --vis viewer+wandb). The problem occurs because interacting with the viewer renders a new image in `_render_img()`, where `model.eval()` is called at the start and `model.train()` at the end, regardless of the initial model state (see [nerfstudio/viewer/render_state_machine.py#L151](https://github.com/nerfstudio-project/nerfstudio/blob/7a0b8cbc89c0500984b016e3d73201f372ba8ef3/nerfstudio/viewer/render_state_machine.py#L151)). If this happens during the actual eval step of the model, it flips the mode to training during evaluation, causing errors.
Changes made:
- Modified `eval_iteration()` to use the `train_lock`, ensuring a consistent model state …
=> Fix splatfacto crash in eval when using viewer

nerfstudio/scripts/exporter.py
Support for exporting point clouds and tsdf meshes with zipnerf (marching cubes and Poisson mesh methods still unsupported)
- [PR](https://github.com/SuLvXiangXin/zipnerf-pytorch/pull/109) to the zipnerf-pytorch repo with relevant changes
- Updated `validate_pipeline` for compatibility with zipnerf
**Verification**
Verified that `ns-export pointcloud ...` and `ns-export tsdf ...` correctly produce point clouds and meshes respectively with zipnerf
Resolves #2974 and #3276
=> Zipnerf point cloud and tsdf mesh export support

nerfstudio/data/utils/data_utils.py
It seems weird to me that depth used float64 while everything else used float32. Moreover, we specify that "Filepath points to a 16-bit or 32-bit depth image", so I don't seem a reason behind converting it to float64. Moreover, the depth prediction is also float32 (`ds_nerf_depth_loss`):
```python
loss = -torch.log(weights + EPS) * torch.exp(-((steps - termination_depth[:, None]) ** 2) / (2 * sigma)) * lengths
```
Here `steps` is float32 while `termination_depth` is float64. This PR changes it to also be float32.
Making this change leads to a small speedup.
Before change (float64):
After change (float32):
This is towards #3446.
=> Change depth from float64 to float32

nerfstudio/data/pixel_samplers.py, nerfstudio/data/utils/pixel_sampling_utils.py
This speeds up the extremely slow `PairPixelSampler`. The main issue seems to be with mask erosion being slow. I managed to speed it up a bit but it still isn't great. I also added the functionality from https://github.com/nerfstudio-project/nerfstudio/pull/2585 to `PairPixelSampler`.
Before any of the changes:
With only erosion:
With both erosion and rejection sampling:
This is an initial step towards #3446
=> Speed up PairPixelSampler

nerfstudio/data/pixel_samplers.py
See #3452 for context.
**NOTE:** This must be merged after #3452. I wanted to specify the #3452 branch as the base branch but somehow couldn't find it in the GitHub UI...
=> Rejection sample mask for patch pixel sampler

nerfstudio/configs/method_configs.py, nerfstudio/models/depth_nerfacto.py
The default pixel sampler for `depth-nerfacto` is `PairPixelSampler`. However, this is very slow due to mask erosion (so slow that it is basically unusable). I managed to speed it up a little here #3452. However, it is still much more efficient to use `PixelSampler`. Moreover, `PairPixelSampler` is only needed when using `SPARSENERF_RANKING` as the depth loss, but the default value is `DS_NERF`, which doesn't require `PairPixelSampler`. Hence, with the default depth loss, most people will be much better off with `PixelSampler` instead of `PairPixelSampler`.
I tested with both depth and masks using 50 images of resolution 1920x1440. Note, that `PairPixelSampler` is only slow when training with masks due to the need for mask erosion.
With `PairPixelSampler`:
With `PixelSampler`:
Closes …
=> Make PixelSampler the depth-nerfacto default

nerfstudio/data/datasets/depth_dataset.py
This makes the `DepthDataset` consistent with the `SDFDataset` and `SemanticDataset`. From my experiments, this also reduces VRAM for `depth-nerfacto` without affecting training speed.
A step towards #3446.
=> Keep depth_image on CPU

nerfstudio/scripts/datasets/process_project_aria.py
@AntonioMacaronio this has been helpful for some of datasets recently. Does it make sense to you? ( I know there's also the other open Aria + data processing PRs )
=> Add `max_frames` + `max_output_size` arguments for Aria data processing

nerfstudio/exporter/tsdf_utils.py, nerfstudio/scripts/exporter.py
I found the TSDF mesh quality to be highly dependent on the TSDF grid location and resolution. Currently, the user is responsible for providing a tight bounding box around the object to ensure good TSDF grid resolution in the areas of interest. However, this is often inconvenient and slow. It might also be hard to achieve when the NeRF is trained on a server for which the viewer isn't available.
In this PR, I suggest a simple solution for refining a rough bounding box estimate using the computed bounding box of the original mesh. In practice, I found this to lead to big improvements.
Note that this assumes that the density estimates are good enough to prevent floaters far from the object. I set the option to False by default, as this will be an issue if no special care is taken.
I trained …
=> Add option for refining the TSDF using the mesh's AABB

pyproject.toml
Don't think it's necessary to pin gsplat to 1.3.0.
=> update gsplat version to >=1.3.0

nerfstudio/viewer/render_state_machine.py
There were some crashes in the viewer when the training state was set back to train(), instead of keeping the prior state of the model.
=> Properly reset train state after render lock in viewer

nerfstudio/process_data/equirect_utils.py
I am trying to process an equirect video using `--crop-bottom=0.2` to remove myself from the bottom portion of the frames.
```bash
ns-process-data video \
--camera-type equirectangular \
--images-per-equirect 8 \
--crop-bottom 0.2 \
...
```
Example frame:
However, I get training images that include my body:
I was able to identify an error in this function: https://github.com/nerfstudio-project/nerfstudio/blob/6b60855003011b2ca23c2fe3f8e2ca6314c69924/nerfstudio/process_data/equirect_utils.py#L213-L230
`bound_arr` is initially the array `[-45, 0, 45]`, which means that it will generate perspective training images using 120 deg FoV cameras pointed at altitudes -45, 0, and 45 degrees. However, with `--crop-bottom=0.2` we end up with `bound_arr == [-57.75, -25.5, -6.0]` at the end of the …
=> Fix: `--crop-bottom` for equirect data

nerfstudio/engine/trainer.py
The original code causes iteration to go over max_num_iterations, causing the progress tracker to be unable to estimate the time needed to finish, and causing unwanted extra iterations. Issue happens when pre-trained checkpoints are loaded.
=> Fix: number of iterations wasn't set correctly (num_iterations directly set to equal to max_num_iterations)

nerfstudio/field_components/encodings.py, nerfstudio/model_components/renderers.py, nerfstudio/models/splatfacto.py, nerfstudio/utils/math.py, nerfstudio/utils/spherical_harmonics.py, tests/field_components/test_encodings.py, tests/utils/test_spherical_harmonics.py
Nothing else currently uses some of the SH utils, but it might make sense to get them out of splatfacto.
I also moved the k nearest neighbors to utils since it doesn't depend on the model class.
=> Move util functions out of splatfacto

pixi.toml
The `depends_on` will be deprecated in the next pixi version. This syntax has been supported for a while now, so I think a migration won't cause too many issues :) Was a failure in our downstream tests :)
=> refactor: use depends-on instead of depends_on

docs/developer_guides/new_methods.md, pyproject.toml, tests/plugins/test_registry.py
In higher version of tyro(>0.9.3), the cli cannot recognize the following config definition:
```python
"""Use the same proposal network. Otherwise use different ones."""
proposal_net_args_list: List[Dict] = field(
default_factory=lambda: [
{"hidden_dim": 16, "log2_hashmap_size": 17, "num_levels": 5, "max_res": 128, "use_linear": False},
{"hidden_dim": 16, "log2_hashmap_size": 17, "num_levels": 5, "max_res": 256, "use_linear": False},
]
)
```
`ns-train nerfacto --pipeline.model.proposal-net-args-list.0.hidden-dim 1`
1. In `typo==0.9.2`:
2. In `typo>0.9.2`:
=> Fix cli bug in high version of tyro

nerfstudio/scripts/exporter.py
Since the [dataloading PR](https://github.com/nerfstudio-project/nerfstudio/pull/3216) moved the pixel sampling process outside of being a datamanager field and into RayBatchStream, some assertions that test this will fail. This PR double checks the datamanager type before performing assertions when using `ns-export pointcloud` or `ns-export poisson` 
This addresses issues such as https://github.com/nerfstudio-project/nerfstudio/issues/3586
=> Fixing Assertion issues when exporting NeRFs to poisson meshes and pointclouds

.github/workflows/core_code_checks.yml
**Background**
- Since February 1st 2025, the github actions for Nerfstudio has been broken as the current version of the cache service has been completely [deprecated](https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down). More information here: 
https://github.com/actions/cache/discussions/1510
**Overview of Changes**
- One line change from v2 to v3
=> Updating github actions cache version

pyproject.toml
Relax the pin on the protobuf dependency to allow up to v5.
=> Allow up to v5 of protobuf
